load preparse.maude
load Gramatica_def.maude
load file.maude

fmod PARSING is
 pr META-LEVEL .
 pr CONVERSION .
 pr PREPARSE .

 ***pr datos_primitivos .

---  sort ParsingRes .
---  op <_> : Term -> ParsingRes [ctor] .

 vars T T1 T1' T2 T2' T3 T3' T4 T4' T5 T5' T6 T6' T7 T7' : Term .
 var  TL : TermList .
 var  Ct : Constant .
 var  S : String .
 var  F : Float .
 vars Q Q' : Qid .
 var  I : Int .
 vars St St' St'' St''' : String .
 vars  N N' : Nat .

 op parse : Term -> Term .
 ***eq parse(T) = parse(upModule('campos_modificables, true), T) .
 ***eq parse(T) = parse(T) .

 ***op parse : Term -> ParsingRes .
 ceq parse('scilla-version_______[T1, T2, T3, T4, T5, T6, T7]) = 'Contrato_______[T1', T2', T3', T4', T5', T6', T7']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) /\
     T4' := parse(T4) /\
     T5' := parse(T5) /\
     T6' := parse(T6) /\
     T7' := parse(T7)  .
--- ceq parse('scilla-version__[T1, T2]) = 'Contrato__[T1', T2']
---   if T1' := parse(T1) /\ 
---      T2' := parse(T2).
 ceq parse('token[T]) = upTerm(F)
  if Q := downQid(T) /\
     S := string(Q) /\
     F := float(S) .
 ceq parse('token[T]) = upTerm(F)
  if Q := downQid(T) /\
     S := string(Q) /\
     rat(S, 10) :: Nat /\
     F := float(S + ".0") .
 ceq parse('token[T]) = upTerm(St)
  if Q := downQid(T) /\
     S := string(Q) /\
     N := find(S, "\"", 0) /\
     St := substr(S, N + 1, sd(length(S), 2)) /\
     St :: String [print St]  .
 ceq parse('token[T]) = T
  if Q := downQid(T) /\
     S := string(Q) /\
     not (float(S) :: Float) /\
     not (rat(S, 10) :: Nat)  .


 ***eq parse('bubble[TL]) = TL .


 ceq parse('_=_;[T1, T2]) = '_=_;[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('_+_[T1, T2]) = '_+._[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ***ENTEROS
 ceq parse('eq__[T1, T2]) = '_==._[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('add__[T1, T2]) = '_+._[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('sub__[T1, T2]) = '_-_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('mul__[T1, T2]) = '_*_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('div__[T1, T2]) = '_/_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('rem__[T1, T2]) = '_rem_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('lt__[T1, T2]) = '_<._[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('pow__[T1, T2]) = '_^_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('isqrt_[T1]) = 'raiz_[T1']
  if T1' := parse(T1) .
 ceq parse('to-nat_[T1]) = 'to-nat_[T1']
  if T1' := parse(T1) .

 ***STRINGS
 ceq parse('concat__[T1, T2]) = '_++_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('substr___[T1, T2, T3]) = 'substr___[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .
 ceq parse('to-string_[T1]) = 'to-string_[T1']
  if T1' := parse(T1) .
 ceq parse('strlen_[T1]) = 'length_[T1']
  if T1' := parse(T1) .

 ***HASHES
 ceq parse('sha256hash_[T1]) = 'sha256hash_[T1']
  if T1' := parse(T1) .
 ceq parse('schnorr-verify___[T1, T2, T3]) = 'schnorr-verify___[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .
 ceq parse('ecdsa-verify___[T1, T2, T3]) = 'ecdsa-verify___[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .

 ***MAPS
 ceq parse('Emp__[T1, T2]) = 'Emp__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('Map__[T1, T2]) = 'Map__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('`[_`][T1]) = 'posicion_[T1']
  if T1' := parse(T1) .
 ceq parse('put___[T1, T2, T3]) = 'put___[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .
 ceq parse('__:=_[T1, T2, T3]) = 'insertar___[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parseL(T2) /\
     T3' := parse(T3) .
 ceq parse('_<-__[T1, T2, T3]) = 'obtener___[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parseL(T3) .
 ceq parse('get__[T1, T2]) = 'get__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('contains__[T1, T2]) = 'contains__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('_<-exists__[T1, T2, T3]) = 'existe___[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parseL(T3) .
 ceq parse('remove__[T1, T2]) = 'remove__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('delete__[T1, T2]) = 'delete__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parseL(T2) .

 ***BNUM
 ceq parse('blt__[T1, T2]) = '_<._[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('badd__[T1, T2]) = '_+._[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('bsub__[T1, T2]) = '_-_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .

 ***DATOS ALGEBRAICOS
 ***Option
 ceq parse('None`{_`}[T1]) = 'None`{_`}[T1']
  if T1' := parse(T1) .
 ceq parse('Some`{_`}_[T1, T2]) = 'Some__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('Some_[T1]) = 'Some_[T1']
  if T1' := parse(T1) .
 ceq parse('Option_[T1]) = 'Option_[T1']
  if T1' := parse(T1) .
 ***Listas
 ceq parse('Nil`{_`}[T1]) = 'Nil`{_`}[T1']
  if T1' := parse(T1) .
 ceq parse('Cons`{_`}__[T1, T2, T3]) = 'Cons___[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .
 ***Pares
 ceq parse('Pair`{__`}__[T1, T2, T3, T4]) = 'Pair____[T1', T2', T3', T4']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) /\ 
     T4' := parse(T4) .
 ceq parse('Pair__[T1, T2]) = 'Pair__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ***Naturales
 ceq parse('Succ_[T1]) = 'Sucesor_[T1']
  if T1' := parse(T1) .

 ***PARÁMETROS INMUTABLES
 ceq parse('_:_[T1, T2]) = '_:_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
---  ceq parse(M, '_`,_[T1, T2]) = M2, 'ListaParamInm__[T1', T2']
---   if M1, T1' := parse(M, T1) /\
---      M2, T2' := parse(M1, T2) .
 eq parse('_`,_[TL]) = '_`,_[parseL(TL)]  .

 ***CAMPOS MODIFICABLES
 ceq parse('field_=_[T1, T2]) = 'campo_=_[T1', T2'] 
  if T1'  := parse(T1) /\
     T2'  := parse(T2) .
 eq parse('__[TL]) = '__[parseL(TL)] .

 ***EXPRESIONES
 ceq parse('let_=_[T1, T2]) = 'let__[T1', T2'] 
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('let_=_in_[T1, T2, T3]) = 'let__in_[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .
 ceq parse('fun`(_`)=>_[T1, T2]) = 'funcion__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('_=__[T1, T2, T3]) = 'aplicarFuncion___[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .

 ceq parse('`(_`)[TL]) = 'aplicarF_[TL]
  if TL := parseL(TL) .
 

 ceq parse('@__[T1, T2]) = '@__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('builtin_[T1]) = 'builtin_[T1']
  if T1' := parse(T1) .
 ceq parse('|_=>_[T1, T2]) = 'opcionMatch__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('match_with_end[T1, T2]) = 'match__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .

 ***DECLARACIONES
 ceq parse('_<-_[T1, T2]) = 'guardar__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('_:=_[T1, T2]) = 'actualizar__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('_<-&BLOCKNUMBER[T1]) = '_<-&BLOCKNUMBER[T1']
  if T1' := parse(T1) .
 ceq parse('_=_[T1, T2]) = '_=_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('forall__[T1, T2]) = 'forall__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('send_[T1]) = 'enviar_[T1']
  if T1' := parse(T1) .
 ceq parse('event_[T1]) = 'evento_[T1']
  if T1' := parse(T1) .
 eq parse('_;_[('_:_[T1, T2], TL)]) = '_;_[parse('_:_[T1, T2]), parseL(TL)] .
 eq parse('_;_[TL]) = '__[parseL(TL)] .


 ***COMUNICACIONES 
 ceq parse('`{_;_`}[T1, T2]) = '`{_;_`}[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('-recipient:_[T1]) = 'dirEnvio_[T1']
  if T1' := parse(T1) .
 ceq parse('-amount:_[T1]) = 'cantidadEnvio_[T1']
  if T1' := parse(T1) .
 ceq parse('`{_;_;_;_`}[T1, T2, T3, T4]) = '`{_;_;_;_`}[T1', T2', T3', T4']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) /\
     T4' := parse(T4) .

 ***TRANSICIONES Y PROCEDIMIENTOS
 ceq parse('procedure_`(_`)_end[T1, T2, T3]) = 'procedimiento___end[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .
 ceq parse('transition_`(_`)_end[T1, T2, T3]) = 'transicion___end[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .

***BOOLUTILS
 ceq parse('andb__[T1, T2]) = '_and_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('_.andb__[T1, T2, T3]) = '_and.__[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .
 ceq parse('orb__[T1, T2]) = '_or_[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('_.orb__[T1, T2, T3]) = '_or.__[T1', T2', T3']
  if T1' := parse(T1) /\
     T2' := parse(T2) /\
     T3' := parse(T3) .
 ceq parse('negb_[T1]) = 'negb_[T1']
  if T1' := parse(T1) .
 ceq parse('_.negb_[T1, T2]) = 'negb.__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .
 ceq parse('bool-to-string_[T1]) = 'bool-to-string_[T1']
  if T1' := parse(T1) .
ceq parse('_.bool-to-string_[T1, T2]) = 'bool-to-string.__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parse(T2) .

 ***ADTS
 ceq parse('|_[T1]) = '|_[T1']
  if T1' := parse(T1) .
 ceq parse('type_=_[T1, T2]) = 'tipo__[T1', T2']
  if T1' := parse(T1) /\
     T2' := parseL(T2) .

 ***Errores
 ceq parse('throw_[T1]) = 'throw_[T1']
  if T1' := parse(T1) .

 ceq parse('library_[T1]) = 'NombreLibreria_[T1']
  if T1' := parse(T1) .
 ceq parse('contract_[T1]) = 'NombreContrato_[T1']
  if T1' := parse(T1) .
 ceq parse('import_[T1]) = 'import_[T1']
  if T1' := parse(T1) .


 ceq parse(T) = Q'
    if St := string(T) /\
    N := find(St, "@", 0) /\ 
    St' := substr(St, 0, N) /\
    St'' := substr(St, N + 1, length(St)) /\
    N' := find(St'', "@", 0) /\
    St''' := substr(St'', 0, N') /\
    Q' := qid(St' + St''') .
   

 *** TODO: terminar
 var QL : QidList .
 eq parse(T) = T [owise] .

 op parseL : TermList -> TermList .
 eq parseL(empty) = empty .
 ***eq parseL('bubble[QL]) = QL .

 eq parseL((T, TL)) = parse(T), parseL(TL) .

 op downQid : Term -> [Qid] [memo] .
 eq downQid(Ct)
    = qid(substr(string(getName(Ct)), 1, length(string(getName(Ct))))) .
 


endfm

mod MTP is
 inc STD-STREAM .
 pr  CONVERSION .
 pr META-SIGN .
 pr  LEXICAL .
 pr PARSING .
 inc FILE .

 vars Text Original Read Source : String .
 var  Attrs : AttributeSet .
 vars FHIn FHOut : Oid .
 var  QIL QIL1 : QidList .
 vars T T' : Term .
 var  M : Module .
 vars N N' : Nat .
 var  Ty : Type .
 var  Q : Qid .

 *** Object and class definition
 op EXAMPLE : -> Cid [ctor] .
 op example : -> Oid [ctor] .

 op noFile : -> Oid [ctor] .

 *** Attributes
 op file:_ : Oid -> Attribute [ctor] .
 op read:_ : String -> Attribute [ctor] .
 op state:_ : State -> Attribute [ctor] .
 op terms:_ : TermList -> Attribute [ctor gather (&)] .

 sort State .
 ops idle reading parsing pedirInfo : -> State [ctor] .

 *** Run command
 op run : -> Configuration [ctor] .

 ***                        ***
 ***          LOAD          ***
 ***                        ***

 crl [loadComm] :
    gotLine(example, stdin, Text)
    < example : EXAMPLE | Attrs >
 => < example : EXAMPLE | Attrs >
    openFile(fileManager, example, Source, "r")
  if Q := tokenize(Text) /\
     Source := printTokens(Q) .

 crl [loadCommERROR] :
    gotLine(example, stdin, Text)
    < example : EXAMPLE | Attrs >
 => < example : EXAMPLE | Attrs >
    write(stdout, example, "File name incorrect.\n")
  if Q QIL := tokenize(Text) /\
     QIL =/= nil .

 rl [openedFile] :
    openedFile(example, fileManager, FHIn)
    < example : EXAMPLE | file: noFile, state: idle, Attrs >
 => < example : EXAMPLE | file: FHIn, state: reading, Attrs >
    getLine(FHIn, example) .

 rl [openFileError] :
    fileError(example, fileManager, Text)
    < example : EXAMPLE | Attrs >
 => < example : EXAMPLE | Attrs >
    write(stdout, example, Text + "\n") .

 ***                           ***
 ***          GotLine          ***
 ***                           ***


rl [newLine] :
   gotLine(example, FHIn, Text)
   < example : EXAMPLE | file: FHIn, read: Read, state: reading, Attrs >
=> if Text == ""
   then < example : EXAMPLE | file: FHIn, read: Read, state: parsing, Attrs > 
        closeFile(FHIn, example)
   else < example : EXAMPLE | file: FHIn, read: (Read + Text), state: reading, Attrs >
        getLine(FHIn, example)
   fi .

crl [parsing] :
    < example : EXAMPLE | read: Read, state: parsing, Attrs >
 => < example : EXAMPLE | read: "", state: pedirInfo, Attrs >
    write(stdout, example, "Parsed.\n")
 if Read =/= "" /\
    QIL := tokenize(Read) /\
    QIL1 := preparse(QIL) /\
    {T, Ty} := metaParse(GRAMMAR, QIL1, anyType) /\
    T' := parse(T) [print QIL1 T "\nParseado: " T'] .

rl [pedirParametros] :
    < example : EXAMPLE | file: noFile, state: pedirInfo, read: "", Attrs >
 => < example : EXAMPLE | read: "", state: idle, Attrs >
    getLine(stdin, example, "Introduce los parametros>") .


 ***                              ***
 ***          closedFile          ***
 ***                              ***

 rl [closedFile] :
    closedFile(example, FHIn)
    < example : EXAMPLE | file: FHIn, Attrs >
 => < example : EXAMPLE | file: noFile, Attrs > .

 ***                          ***
 ***          WROTE           ***
 ***                          ***

 rl [wrote] :
    wrote(example, stdout)
    < example : EXAMPLE | file: noFile, Attrs >
 => < example : EXAMPLE | file: noFile, Attrs > .

 ***                        ***
 ***          RUN           ***
 ***                        ***

 eq run =
    <> < example : EXAMPLE | file: noFile, read: "", state: idle, terms: empty >
    getLine(stdin, example, "Introduce file name> ") .
endm



red metaParse(GRAMMAR, tokenize("If xxw\nThen 4 = 4 + w ;\nElse z = 4.5 ;\nFi"), anyType) .
red metaParse(GRAMMAR, tokenize("scilla-version 0 (a : String , b : BNum , c : Uint32) cv | None => @ a Uint32 | None => @ a Uint32"), anyType) .
red metaParse(GRAMMAR, tokenize("type Unit = | Unit let zero = Uint128 0"), anyType) .
red metaParse(GRAMMAR, tokenize("a = builtin eq a a ; match a with | true => e = {-eventname: \"setHello\" ; code : not_owner_code} ; event e end"), anyType) .
red metaParse(GRAMMAR, tokenize("let a = fun (msg : Message) => let nil_msg = Nil {Message} in Cons {Message} msg nil_msg let code_success = Uint32 0"), anyType) .
red metaParse(GRAMMAR, tokenize("transition addMember (name : String , addr : ByStr20 , memberType : Uint32) match is_authorized with | true => valid_type = let three = Uint32 3 in builtin lt memberType three ; match valid_type with | true => p = Pair {(String) (Uint32)} name memberType ; members[addr] := p ; msg = {-tag: \"\" ; -recipient: _sender ; -amount: Uint128 0 ; code : code_success} ; msgs = one_msg msg ; send msgs  | false =>  send msgs end end end"), anyType) .
red metaParse(GRAMMAR, tokenize("transition setHello (msg : String) is_owner = builtin eq owner _sender ; match is_owner with | false => e = {-eventname: \"setHello\" ; code : not_owner_code} , event e | true => welcome_msg := msg , e = {-eventname: \"setHello\" ; code : set_hello_code} , event e end end"), anyType) .
red metaParse(GRAMMAR, tokenize("is_authorized = builtin eq _sender owner "), anyType) .
red metaParse(GRAMMAR, tokenize("match is_owner with | false => e = {-eventname: \"setHello\" ; code : not_owner_code} ; event e | true => welcome_msg := msg ; e = {-eventname: \"setHello\" ; code : set_hello_code} ; event e end"), anyType) .
red metaParse(GRAMMAR, tokenize("fun (some_val : Option Uint128) => match some_val with | Some val => val | None => zero end"), anyType) .
red metaParse(GRAMMAR, tokenize("match result with | CodeIsSender => (Int32 -1) end"), anyType) .
red metaParse(GRAMMAR, tokenize("field allowances : Map ByStr20 (Map ByStr20 Uint128) = Emp ByStr20 (Map ByStr20 Uint128)"), anyType) .
red metaParse(GRAMMAR, tokenize("transition whoami(lpv) author <- author_name ; twitter <- twitter_id ; e = {-eventname: \"Whoami\" ; author_name : author ; twitter_id : twitter} ; event e end"), anyType) .
red metaParse(GRAMMAR, tokenize("procedure IsNotSender(address : ByStr20) is_sender = builtin eq _sender address ; match is_sender with | true => err = CodeIsSender | false => ev end end"), anyType) .
red metaParse(GRAMMAR, tokenize("let get_val = fun (some_val : Option Uint128) => match some_val with | Some val => val | None => zero end"), anyType) .
red metaParse(GRAMMAR, tokenize("let make_error_event = fun (result : Error) => let result_code =  match result with | CodeNotAuthorised    => Int32 -1 | CodeNotFound         => Int32 -2  | CodeTokenExists      => Int32 -3 | CodeUnexpectedError  => Int32 -4 end"), anyType) .
red metaParse(GRAMMAR, tokenize("match is_owner with | false =>  e = {-eventname: \"setHello\" ; code : not_owner_code} ;  event e | true =>  welcome_msg := msg ;  e = {-eventname: \"setHello\" ; code : set_hello_code} ;   event e end"), anyType) .
red metaParse(GRAMMAR, tokenize("Uint32 1"), anyType) .
red parse('__['Uint32.@TipoEntero@,'s_['0.Zero]]) .
***red metaParse(Sistema, tokenize("[a = b + c , mv]"))
red preparse('mone '= 'one_msg 'm ';) .

--- ***Contrato1
--- red metaRewrite(upModule('REGLAS, true), '`[_`,_`,_`]['Contrato_______['0.Zero,'iv.Importacion,'__['NombreLibreria_[''HelloWorld.Qid],
---     '__['let__[''not_owner_code.Qid,'__['Uint32.TipoEntero,'s_['0.Zero]]],'let__[
---     ''set_hello_code.Qid,'__['Uint32.TipoEntero,'s_^2['0.Zero]]]]],'NombreContrato_[''HelloWorld.Qid],
---     '_:_[''owner.Qid,'ByStr20.NombreTipo],'campo_=_['_:_[''welcome_msg.Qid,'String.NombreTipo],'"".String],
--- 	'__['transicion___end[''setHello.Qid,'_:_[''msg.Qid,'String.NombreTipo],'__['_=_[''is_owner.Qid,'builtin_['_==._[''owner.Qid,''_sender.Qid]]],'match__[''is_owner.Qid,
---     '__['opcionMatch__['false.Bool,'__['_=_[''e.Qid,'`{_;_`}['-eventname:_['"setHello".String],'_:_[''code.Qid,
---     ''not_owner_code.Qid]]],'evento_[''e.Qid]]],'opcionMatch__['true.Bool,'__['actualizar__[''welcome_msg.Qid,
---     ''msg.Qid],'__['_=_[''e.Qid,'`{_;_`}['-eventname:_['"setHello".String],'_:_[''code.Qid,''set_hello_code.Qid]]],
---     'evento_[''e.Qid]]]]]]]],
---     'transicion___end[''getHello.Qid,'lpv.ListaParamInm,
---     '__['guardar__[''r.Qid,''welcome_msg.Qid],'__['_=_[''e.Qid,'`{_;_`}['-eventname:_[
---     '"getHello".String],'_:_[''msg.Qid,''r.Qid]]],'evento_[''e.Qid]]]]]],'mv.Memoria,'mv.Memoria], unbounded) .

--- ***Ejecutar transicion 1
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''welcome_msg.Qid,'"".String],'`[_=>_`][''owner.Qid,'s_^2['0.Zero]],
---     '`[_=>_`][''not_owner_code.Qid,'s_['0.Zero]],'`[_=>_`][''set_hello_code.Qid,'s_^2['0.Zero]]],
---     '`[_`,_`,_`,_`,_`][''setHello.Qid,'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['`[_=>_`][''is_owner.Qid,'`[_`]['_==._[
---     ''_sender.Qid,''owner.Qid]]],'`[_=>_`][''is_owner.Qid,'__['`[_=>_`]['false.Bool,'__['`[_=>_`][''e.Qid,'__['`[_=>_`][
---     ''eventname.Qid,'"setHello".String],'`[_=>_`][''code.Qid,'s_['0.Zero]]]],'`[_=>_`][''evento.Qid,''e.Qid]]],
---     '`[_=>_`]['true.Bool,'__['Actualizar`[_`,_`][''welcome_msg.Qid,''msg.Qid],'`[_=>_`][''e.Qid,'__['`[_=>_`][
---     ''eventname.Qid,'"setHello".String],'`[_=>_`][''code.Qid,'s_^2['0.Zero]]]],'`[_=>_`][''evento.Qid,''e.Qid]]]]]],
---     '__['`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,'s_^2['0.Zero]],'`[_=>_`][''msg.Qid,
---     'String.NombreTipo]]]], unbounded) .

--- ***Ejecutar transicion 2
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''welcome_msg.Qid,'"".String],'`[_=>_`][''owner.Qid,'ByStr20.NombreTipo],
---     '`[_=>_`][''not_owner_code.Qid,'s_['0.Zero]],'`[_=>_`][''set_hello_code.Qid,'s_^2['0.Zero]]],'`[_`,_`,_`,_`,_`][''getHello.Qid,'lpv.ListaParamInm,
---     'ldv.ListaDeclaraciones,'__['`[_=>_`][''r.Qid,''welcome_msg.Qid],'`[_=>_`][''e.Qid,'__['`[_=>_`][''eventname.Qid,
---     '"getHello".String],'`[_=>_`][''msg.Qid,''r.Qid]]],'`[_=>_`][''evento.Qid,''e.Qid]],'__['`[_=>_`][''_amount.Qid,
---     'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,'ByStr20.NombreTipo]]]], unbounded) .

--- ***Contrato8
--- red metaRewrite(upModule('REGLAS, true), '`[_`,_`,_`]['Contrato_______['0.Zero, 'import_['PairUtils.LibImportar],'__['NombreLibreria_[''Schnorr.Qid],
---     'let__[
---     ''one_msg.Qid,'funcion__['_:_[''msg.Qid,'Message.NombreTipo],'let__in_[''nil_msg.Qid,'Nil`{_`}[
---     'Message.NombreTipo],'Cons___['Message.NombreTipo,''msg.Qid,''nil_msg.Qid]]]]],'NombreContrato_[''HelloWorld.Qid],
---     'lpv.ListaParamInm,'campo_=_['_:_[''pub_key.Qid,'Option_['ByStr33.NombreTipo]],'None`{_`}['ByStr33.NombreTipo]],
---     'transicion___end[''verify.Qid,'_`,_['_:_[''msg.Qid,'ByStr.NombreTipo],'_:_[''sig.Qid,'ByStr64.NombreTipo]],
---     '__['guardar__[''pubk_o.Qid,''pub_key.Qid],'match__[''pubk_o.Qid,'__['opcionMatch__['Some_[''pubk.Qid],'__['_=_[''sig.Qid,
---     'builtin_['schnorr-verify___[''pubk.Qid,''msg.Qid,''sig.Qid]]],'match__[''sig.Qid,'__['opcionMatch__['true.Bool,
---     '__['_=_[''m.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__[
---     'Uint128.TipoEntero,'0.Zero]],'_:_[''status.Qid,''"verification successful".Qid]]],'__['_=_[''mone.Qid,'aplicarF_[
---     '__[''one_msg.Qid,''m.Qid]]],'enviar_[''mone.Qid]]]],'opcionMatch__['false.Bool,'__['_=_[''m.Qid,
---     '`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,
---     '0.Zero]],'_:_[''status.Qid,''"verification failed".Qid]]],'__['_=_[''mone.Qid,'aplicarF_['__[''one_msg.Qid,
---     ''m.Qid]]],'enviar_[''mone.Qid]]]]]]]],'opcionMatch__['None.Option,'__['_=_[''m.Qid,'`{_;_;_;_`}[
---     '-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[
---     ''status.Qid,''"no key error".Qid]]],'__['_=_[''mone.Qid,'aplicarF_['__[''one_msg.Qid,''m.Qid]]],'enviar_[
---     ''mone.Qid]]]]]]]]],'mv.Memoria,'mv.Memoria], unbounded) .

--- ***Ejecutar transicion 1
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''pub_key.Qid,'None.Option],'Importaciones`[_`][
---     'PairUtils.LibImportar],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][''msg.Qid,'Message.NombreTipo],'`[_=>_`,_`][''nil_msg.Qid,'Nil`{_`}[
---     'Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,''nil_msg.Qid]]]]],'`[_`,_`,_`,_`,_`][''verify.Qid,'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['`[_=>_`][''pubk_o.Qid,
---     ''pub_key.Qid],'`[_=>_`][''pubk_o.Qid,'__['`[_=>_`]['Some_[''pubk.Qid],'__['`[_=>_`][''sig.Qid,'`[_`][
---     'schnorr-verify___[''pubk.Qid,''msg.Qid,''sig.Qid]]],'`[_=>_`][''sig.Qid,'__['`[_=>_`]['true.Bool,'__['`[_=>_`][
---     ''m.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,
---     '0.Zero],'`[_=>_`][''status.Qid,'"verification successful".String]]],'`[_=>_`][''mone.Qid,'AplicarF`[_`,_`][
---     ''one_msg.Qid,''m.Qid]],'`[_=>_`][''enviar.Qid,''mone.Qid]]],'`[_=>_`]['false.Bool,'__['`[_=>_`][''m.Qid,'__[
---     '`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],
---     '`[_=>_`][''status.Qid,'"verification failed".String]]],'`[_=>_`][''mone.Qid,'AplicarF`[_`,_`][''one_msg.Qid,
---     ''m.Qid]],'`[_=>_`][''enviar.Qid,''mone.Qid]]]]]]],'`[_=>_`]['None.Option,'__['`[_=>_`][''m.Qid,'__['`[_=>_`][
---     ''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][
---     ''status.Qid,'"no key error".String]]],'`[_=>_`][''mone.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''m.Qid]],'`[_=>_`][
---     ''enviar.Qid,''mone.Qid]]]]]],'__['`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,
---     'ByStr20.NombreTipo],'`[_=>_`][''msg.Qid,'ByStr.NombreTipo],'`[_=>_`][''sig.Qid,'ByStr64.NombreTipo]]]], unbounded) .

--- ***Contrato10
--- red metaRewrite(upModule('REGLAS, true), '`[_`,_`,_`]['Contrato_______['0.Zero, 'iv.Importacion,'__['NombreLibreria_[''LoveZilliqa.Qid],
---     '__['let__[''one.Qid,'__[
---     'Uint256.TipoEntero,'s_['0.Zero]]],'let__[''tt.Qid,'true.Bool]]],'NombreContrato_[''LoveZilliqa.Qid],
---     '_`,_['_:_[''authorName.Qid,'String.NombreTipo],'_:_[''twitterID.Qid,'String.NombreTipo]],
---     '__['campo_=_['_:_[
---     ''author_name.Qid,'String.NombreTipo],'aplicarF_[''authorName.Qid]],'__['campo_=_['_:_[''twitter_id.Qid,
---     'String.NombreTipo],'aplicarF_[''twitterID.Qid]],'__['campo_=_['_:_[''upvote_counter.Qid,
---     'Uint256.TipoEntero],'__['Uint256.TipoEntero,'0.Zero]],'campo_=_['_:_[''vote_map.Qid,'Map__[
---     'ByStr20.NombreTipo,'Bool.NombreTipo]],'Emp__['ByStr20.NombreTipo,'Bool.NombreTipo]]]]],
---     '__['transicion___end[''upvote.Qid,'lpv.ListaParamInm,'__['existe___[''has_voted.Qid,''vote_map.Qid,'posicion_[
---     ''_sender.Qid]],'__['guardar__[''current_vote_count.Qid,''upvote_counter.Qid],'match__[''has_voted.Qid,
---     '__['opcionMatch__['true.Bool,'__['_=_[''e.Qid,'`{_;_`}['-eventname:_['"AlreadyVoted".String],'_:_[
---     ''current_upvote_count.Qid,''current_vote_count.Qid]]],'evento_[''e.Qid]]],'opcionMatch__['false.Bool,'__['_=_[
---     ''new_vote_count.Qid,'builtin_['_+._[''current_vote_count.Qid,''one.Qid]]],'__['insertar___[''vote_map.Qid,
---     'posicion_[''_sender.Qid],''tt.Qid],'__['actualizar__[''upvote_counter.Qid,''new_vote_count.Qid],'__['_=_[''e.Qid,
---     '`{_;_`}['-eventname:_['"Voted".String],'_;_['_:_[''shoutout.Qid,'"Zilliqa loves you!".String],
---     '_:_[''new_vote_count.Qid,''new_vote_count.Qid]]]],'evento_[''e.Qid]]]]]]]]]]],
---     'transicion___end[''whoami.Qid,
---     'lpv.ListaParamInm,'__['guardar__[''author.Qid,''author_name.Qid],'__['guardar__[''twitter.Qid,''twitter_id.Qid],
---     '_=_[''e.Qid,'`{_;_`}['-eventname:_['"Whoami".String],'_;_['_:_[''author_name.Qid,''author.Qid],'_:_[''twitter_id.Qid,''twitter.Qid]]]],'evento_[
---     ''e.Qid]]]]]],'mv.Memoria,'mv.Memoria], unbounded) .

--- ***Ejecutar transicion 1
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''author_name.Qid,'AplicarF`[_`][''authorName.Qid]],'`[_=>_`][''one.Qid,'s_[
---     '0.Zero]],'`[_=>_`][''authorName.Qid,'"Laura".String],'`[_=>_`][''twitterID.Qid,'"Hola".String],'`[_=>_`][
---     ''tt.Qid,'true.Bool],'`[_=>_`][''twitter_id.Qid,'AplicarF`[_`][''twitterID.Qid]],'`[_=>_`][''upvote_counter.Qid,
---     '0.Zero],'`[_=>_`][''vote_map.Qid,'empty.Map`{Nat`,Clave`}]],'`[_`,_`,_`,_`,_`][
---     ''upvote.Qid,'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['Existe`[_=>_`,_`][''has_voted.Qid,''vote_map.Qid,
---     'posicion_[''_sender.Qid]],'`[_=>_`][''current_vote_count.Qid,''upvote_counter.Qid],'`[_=>_`][''has_voted.Qid,'__[
---     '`[_=>_`]['true.Bool,'__['`[_=>_`][''e.Qid,'__['`[_=>_`][''eventname.Qid,'"AlreadyVoted".String],'`[_=>_`][
---     ''current_upvote_count.Qid,''current_vote_count.Qid]]],'`[_=>_`][''evento.Qid,''e.Qid]]],'`[_=>_`]['false.Bool,'__[
---     '`[_=>_`][''new_vote_count.Qid,'`[_`]['_+._[''current_vote_count.Qid,''one.Qid]]],'Insertar`[_=>_`,_`][
---     ''vote_map.Qid,''tt.Qid,'posicion_[''_sender.Qid]],'Actualizar`[_`,_`][''upvote_counter.Qid,''new_vote_count.Qid],
---     '`[_=>_`][''e.Qid,'__['`[_=>_`][''eventname.Qid,'"Voted".String],'`[_=>_`][''shoutout.Qid,'"Zilliqa loves you!".String],
---     '`[_=>_`][''new_vote_count.Qid,''new_vote_count.Qid]]],'`[_=>_`][''evento.Qid,''e.Qid]]]]]],'__['`[_=>_`][''_amount.Qid,
---     'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,'s_^2['0.Zero]]]]], unbounded) .

--- ***Ejecutar transicion 2
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''author_name.Qid,'AplicarF`[_`][''authorName.Qid]],'`[_=>_`][''one.Qid,'s_[
---     '0.Zero]],'`[_=>_`][''authorName.Qid,'"Laura".String],'`[_=>_`][''twitterID.Qid,'"Hola".String],'`[_=>_`][
---     ''tt.Qid,'true.Bool],'`[_=>_`][''twitter_id.Qid,'AplicarF`[_`][''twitterID.Qid]],'`[_=>_`][''upvote_counter.Qid,
---     '0.Zero],'`[_=>_`][''vote_map.Qid,'empty.Map`{Nat`,Clave`}]],'`[_`,_`,_`,_`,_`][''whoami.Qid,
---     'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['`[_=>_`][''author.Qid,''author_name.Qid],'`[_=>_`][''twitter.Qid,
---     ''twitter_id.Qid],'`[_=>_`][''e.Qid,'__['`[_=>_`][''eventname.Qid,'"Whoami".String],'`[_=>_`][''author_name.Qid,
---     ''author.Qid],'`[_=>_`][''twitter_id.Qid,''twitter.Qid]]],'`[_=>_`][''evento.Qid,''e.Qid]],'__['`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,'s_^2['0.Zero]]]]], unbounded) .

--- ***Contrato2
--- red metaRewrite(upModule('REGLAS, true), '`[_`,_`,_`]['Contrato_______['0.Zero, 'iv.Importacion,'__['NombreLibreria_[''BookStore.Qid],
---     '__['let__[''one_msg.Qid,
---     'funcion__['_:_[''msg.Qid,'Message.NombreTipo],'let__in_[''nil_msg.Qid,'Nil`{_`}['Message.NombreTipo],'Cons___[
---     'Message.NombreTipo,''msg.Qid,''nil_msg.Qid]]]],'__['let__[''code_success.Qid,'__['Uint32.TipoEntero,'0.Zero]],
---     '__['let__[''code_book_not_found.Qid,'__['Uint32.TipoEntero,'s_['0.Zero]]],'__['let__[''code_not_authorized.Qid,
---     '__['Uint32.TipoEntero,'s_^2['0.Zero]]],'__['let__[''code_invalid_params.Qid,'__['Uint32.TipoEntero,'s_^3[
---     '0.Zero]]],'let__[''code_bookid_exist.Qid,'__['Uint32.TipoEntero,'s_^4['0.Zero]]]]]]]]],'NombreContrato_[''BookStore.Qid],
---     '_`,_['_:_[''owner.Qid,'ByStr20.NombreTipo],'_:_[''storeName.Qid,'String.NombreTipo]],'__[
---     'campo_=_['_:_[''members.Qid,'Map__['ByStr20.NombreTipo,'Pair__['String.NombreTipo,'Uint32.TipoEntero]]],
---     'Emp__['ByStr20.NombreTipo,'Pair__['String.NombreTipo,'Uint32.TipoEntero]]],'__['campo_=_['_:_[
---     ''lastBookID.Qid,'Option_['String.NombreTipo]],'None`{_`}['String.NombreTipo]],'campo_=_['_:_[
---     ''bookInventory.Qid,'Map__['Uint32.TipoEntero,'Pair__['String.NombreTipo,'String.NombreTipo]]],'Emp__[
---     'Uint32.TipoEntero,'Pair__['String.NombreTipo,'String.NombreTipo]]]]],
    
---     '__['transicion___end[''addMember.Qid,'_`,_['_:_[''name.Qid,'String.NombreTipo],'_`,_['_:_[''addr.Qid,'ByStr20.NombreTipo],'_:_[''memberType.Qid,
---     'Uint32.TipoEntero]]],'__['_=_[''is_authorized.Qid,'builtin_['_==._[''_sender.Qid,''owner.Qid]]],'match__[
---     ''is_authorized.Qid,'__['opcionMatch__['true.Bool,'__['_=_[''valid_type.Qid,'let__in_[''three.Qid,'__[
---     'Uint32.TipoEntero,'s_^3['0.Zero]],'builtin_['_<._[''memberType.Qid,''three.Qid]]]],'match__[''valid_type.Qid,'__[
---     'opcionMatch__['true.Bool,'__['_=_[''p.Qid,'Pair____['String.NombreTipo,'Uint32.TipoEntero,''name.Qid,
---     ''memberType.Qid]],'__['insertar___[''members.Qid,'posicion_[''addr.Qid],''p.Qid],'__['_=_[''msg.Qid,'`{_;_;_;_`}[
---     '-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,
---     ''code_success.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[
---     ''msgs.Qid]]]]]],'opcionMatch__['false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[
---     ''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''code_invalid_params.Qid]]],
---     '__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]]]]]],'opcionMatch__[
---     'false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__[
---     'Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''code_not_authorized.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_[
---     '__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msg.Qid]]]]]]]],
    
---     '__['transicion___end[''addBook.Qid,'_`,_['_:_[
---     ''book_title.Qid,'String.NombreTipo],'_`,_['_:_[''author.Qid,'String.NombreTipo],'_:_[''bookID.Qid,
---     'Uint32.TipoEntero]]],'__['guardar__[''books.Qid,''bookInventory.Qid],'__['_=_[''bookExist.Qid,'builtin_[
---     'contains__[''books.Qid,''bookID.Qid]]],'match__[''bookExist.Qid,'__['opcionMatch__['true.Bool,'__['_=_[''msg.Qid,
---     '`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],
---     '_:_[''code.Qid,''code_bookid_exist.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],
---     'enviar_[''msgs.Qid]]]],'opcionMatch__['false.Bool,'__['_=_[''new_book.Qid,'Pair____['String.NombreTipo,
---     'String.NombreTipo,''book_title.Qid,''author.Qid]],'__['insertar___[''bookInventory.Qid,'posicion_[''bookID.Qid],
---     ''new_book.Qid],'__['_=_[''tmp.Qid,'Some__['Uint32.TipoEntero,''bookID.Qid]],'__['actualizar__[''lastBookID.Qid,
---     ''tmp.Qid],'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__[
---     'Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''code_success.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[
---     ''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]]]]]]]]]]],
    
---     '__['transicion___end[''removeBook.Qid,'_:_[
---     ''book_id.Qid,'Uint32.TipoEntero],'delete__[''bookInventory.Qid,'posicion_[''book_id.Qid]]],
    
---     'transicion___end[
---     ''updateBook.Qid,'_`,_['_:_[''book_id.Qid,'Uint32.TipoEntero],'_`,_['_:_[''book_title.Qid,'String.NombreTipo],
---     '_:_[''author.Qid,'String.NombreTipo]]],'__['guardar__[''books.Qid,''bookInventory.Qid],'__['_=_[''exist.Qid,
---     'builtin_['contains__[''books.Qid,''book_id.Qid]]],'match__[''exist.Qid,'__['opcionMatch__['false.Bool,'__['_=_[
---     ''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,
---     '0.Zero]],'_:_[''code.Qid,''code_book_not_found.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,
---     ''msg.Qid]]],'enviar_[''msgs.Qid]]]],'opcionMatch__['true.Bool,'__['_=_[''new_book.Qid,'Pair____[
---     'String.NombreTipo,'String.NombreTipo,''book_title.Qid,''author.Qid]],'__['insertar___[''bookInventory.Qid,
---     'posicion_[''book_id.Qid],''new_book.Qid],'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[
---     ''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''code_success.Qid]]],'__['_=_[
---     ''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]]]]]]]]]]]]],'mv.Memoria,'mv.Memoria], unbounded) .

--- ***Ejecutar transicion 1 
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''owner.Qid,'s_^2['0.Zero]],'`[_=>_`][''storeName.Qid,
---     'String.NombreTipo],'`[_=>_`][''members.Qid,'empty.Map`{Nat`,Clave`}],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][''msg.Qid,'Message.NombreTipo],
---     '`[_=>_`,_`][''nil_msg.Qid,'Nil`{_`}['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,''nil_msg.Qid]]]],'`[_=>_`][
---     ''lastBookID.Qid,'None.Option],'`[_=>_`][''code_success.Qid,'0.Zero],'`[_=>_`][''bookInventory.Qid,'Emp__[
---     'Uint32.TipoEntero,'Pair__['String.NombreTipo,'String.NombreTipo]]],'`[_=>_`][''code_book_not_found.Qid,'s_[
---     '0.Zero]],'`[_=>_`][''code_not_authorized.Qid,'s_^2['0.Zero]],'`[_=>_`][''code_invalid_params.Qid,'s_^3['0.Zero]],
---     '`[_=>_`][''code_bookid_exist.Qid,'s_^4['0.Zero]]],'`[_`,_`,_`,_`,_`][''addMember.Qid,'lpv.ListaParamInm,
---     'ldv.ListaDeclaraciones,'__['`[_=>_`][''is_authorized.Qid,'`[_`]['_==._[''_sender.Qid,''owner.Qid]]],'`[_=>_`][
---     ''is_authorized.Qid,'__['`[_=>_`]['true.Bool,'__['`[_=>_`][''valid_type.Qid,'`[_=>_`,_`][''three.Qid,'s_^3[
---     '0.Zero],'`[_`]['_<._[''memberType.Qid,''three.Qid]]]],'`[_=>_`][''valid_type.Qid,'__['`[_=>_`]['true.Bool,'__[
---     '`[_=>_`][''p.Qid,'Par`[_`,_`][''name.Qid,''memberType.Qid]],'Insertar`[_=>_`,_`][''members.Qid,''p.Qid,'posicion_[
---     ''addr.Qid]],'`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],
---     '`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''code_success.Qid]]],'`[_=>_`][''msgs.Qid,
---     'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['false.Bool,'__[
---     '`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][
---     ''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''code_invalid_params.Qid]]],'`[_=>_`][''msgs.Qid,
---     'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]]]]]],'`[_=>_`]['false.Bool,'__[
---     '`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][
---     ''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''code_not_authorized.Qid]]],'`[_=>_`][''msgs.Qid,
---     'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msg.Qid]]]]]],'__['`[_=>_`][''_amount.Qid,
---     'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,'s_^2['0.Zero]],'`[_=>_`][''name.Qid,'String.NombreTipo],
---     '`[_=>_`][''addr.Qid,'s_^5['0.Zero]],'`[_=>_`][''memberType.Qid,'s_^2['0.Zero]]]]], unbounded) .
--- ***Ejecutar transicion 2
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''owner.Qid,'ByStr20.NombreTipo],'`[_=>_`][''storeName.Qid,
---     'String.NombreTipo],'`[_=>_`][''members.Qid,'empty.Map`{Nat`,Clave`}],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][''msg.Qid,'Message.NombreTipo],
---     '`[_=>_`,_`][''nil_msg.Qid,'Nil`{_`}['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,''nil_msg.Qid]]]],'`[_=>_`][
---     ''lastBookID.Qid,'None.Option],'`[_=>_`][''code_success.Qid,'0.Zero],'`[_=>_`][''bookInventory.Qid,'empty.Map`{Nat`,Clave`}],'`[_=>_`][''code_book_not_found.Qid,'s_[
---     '0.Zero]],'`[_=>_`][''code_not_authorized.Qid,'s_^2['0.Zero]],'`[_=>_`][''code_invalid_params.Qid,'s_^3['0.Zero]],
---     '`[_=>_`][''code_bookid_exist.Qid,'s_^4['0.Zero]]],'`[_`,_`,_`,_`,_`][
---     ''addBook.Qid,'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['`[_=>_`][''books.Qid,''bookInventory.Qid],'`[_=>_`][
---     ''bookExist.Qid,'`[_`]['contains__[''books.Qid,''bookID.Qid]]],'`[_=>_`][''bookExist.Qid,'__['`[_=>_`]['true.Bool,
---     '__['`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][
---     ''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''code_bookid_exist.Qid]]],'`[_=>_`][''msgs.Qid,
---     'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['false.Bool,'__[
---     '`[_=>_`][''new_book.Qid,'Par`[_`,_`][''book_title.Qid,''author.Qid]],'Insertar`[_=>_`,_`][''bookInventory.Qid,
---     ''new_book.Qid,'posicion_[''bookID.Qid]],'`[_=>_`][''tmp.Qid,'Some`[_`][''bookID.Qid]],'Actualizar`[_`,_`][
---     ''lastBookID.Qid,''tmp.Qid],'`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,
---     ''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''code_success.Qid]]],'`[_=>_`][
---     ''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]]]]],'__['`[_=>_`][
---     ''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,'ByStr20.NombreTipo],'`[_=>_`][''book_title.Qid,
---     'String.NombreTipo],'`[_=>_`][''author.Qid,'String.NombreTipo],'`[_=>_`][''bookID.Qid,'s_^2['0.Zero]]]]], unbounded) .
--- ***Ejecutar transicion 3
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''owner.Qid,'ByStr20.NombreTipo],'`[_=>_`][''storeName.Qid,
---     'String.NombreTipo],'`[_=>_`][''members.Qid,'Emp__['ByStr20.NombreTipo,'Pair__['String.NombreTipo,
---     'Uint32.TipoEntero]]],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][''msg.Qid,'Message.NombreTipo],
---     '`[_=>_`,_`][''nil_msg.Qid,'Nil`{_`}['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,''nil_msg.Qid]]]],'`[_=>_`][
---     ''lastBookID.Qid,'None.Option],'`[_=>_`][''code_success.Qid,'0.Zero],'`[_=>_`][''bookInventory.Qid,
---     '_|->_['s_^2['0.Zero],'`[_`,_`]['"Hola".String,'"Hola".String]]],'`[_=>_`][''code_book_not_found.Qid,'s_[
---     '0.Zero]],'`[_=>_`][''code_not_authorized.Qid,'s_^2['0.Zero]],'`[_=>_`][''code_invalid_params.Qid,'s_^3['0.Zero]],
---     '`[_=>_`][''code_bookid_exist.Qid,'s_^4['0.Zero]]],'`[_`,_`,_`,_`,_`][''removeBook.Qid,'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'Eliminar`[_`,_`][
---     ''bookInventory.Qid,'posicion_[''book_id.Qid]],'__['`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][
---     ''_sender.Qid,'ByStr20.NombreTipo],'`[_=>_`][''book_id.Qid,'s_^2['0.Zero]]]]], unbounded) .
--- ***Ejecutar transicion 4
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''owner.Qid,'ByStr20.NombreTipo],'`[_=>_`][''storeName.Qid,
---     'String.NombreTipo],'`[_=>_`][''members.Qid,'empty.Map`{Nat`,Clave`}],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][''msg.Qid,'Message.NombreTipo],
---     '`[_=>_`,_`][''nil_msg.Qid,'Nil`{_`}['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,''nil_msg.Qid]]]],'`[_=>_`][
---     ''lastBookID.Qid,'None.Option],'`[_=>_`][''code_success.Qid,'0.Zero],'`[_=>_`][''bookInventory.Qid,'empty.Map`{Nat`,Clave`}],
---     '`[_=>_`][''code_book_not_found.Qid,'s_['0.Zero]],
---     '`[_=>_`][''code_not_authorized.Qid,'s_^2['0.Zero]],'`[_=>_`][''code_invalid_params.Qid,'s_^3['0.Zero]],
---     '`[_=>_`][''code_bookid_exist.Qid,'s_^4['0.Zero]]],'`[_`,_`,_`,_`,_`][
---     ''updateBook.Qid,'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['`[_=>_`][''books.Qid,''bookInventory.Qid],
---     '`[_=>_`][''exist.Qid,'`[_`]['contains__[''books.Qid,''book_id.Qid]]],'`[_=>_`][''exist.Qid,'__['`[_=>_`][
---     'false.Bool,'__['`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],
---     '`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''code_book_not_found.Qid]]],'`[_=>_`][''msgs.Qid,
---     'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['true.Bool,'__[
---     '`[_=>_`][''new_book.Qid,'Par`[_`,_`][''book_title.Qid,''author.Qid]],'Insertar`[_=>_`,_`][''bookInventory.Qid,
---     ''new_book.Qid,'posicion_[''book_id.Qid]],'`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][
---     ''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''code_success.Qid]]],
---     '`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]]]]],'__[
---     '`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,'ByStr20.NombreTipo],'`[_=>_`][''book_id.Qid,
---     's_^2['0.Zero]],'`[_=>_`][''book_title.Qid,'String.NombreTipo],'`[_=>_`][''author.Qid,'String.NombreTipo]]]], unbounded) .



--- ***Contrato3
--- red metaRewrite(upModule('REGLAS, true), '`[_`,_`,_`]['Contrato_______['0.Zero, 'iv.Importacion,'__['NombreLibreria_[''BookStore.Qid],
---     '__['let__[''one_msg.Qid,
---     'funcion__['_:_[''msg.Qid,'Message.NombreTipo],'let__in_[''nil_msg.Qid,'Nil`{_`}['Message.NombreTipo],'Cons___[
---     'Message.NombreTipo,''msg.Qid,''nil_msg.Qid]]]],

---     '__['let__[''check_update.Qid,
---     'funcion__['_:_[''bs.Qid,'Map__['ByStr20.NombreTipo,'Uint128.TipoEntero]],'funcion__['_:_[''sender.Qid,
---     'ByStr20.NombreTipo],'funcion__['_:_[''amount.Qid,'Uint128.TipoEntero],'let__in_[''c.Qid,'builtin_['contains__[
---     ''bs.Qid,''sender.Qid]],'match__[''c.Qid,'__['opcionMatch__['false.Bool,'let__in_[''bs1.Qid,'builtin_['put___[
---     ''bs.Qid,''sender.Qid,''amount.Qid]],'Some__['Map__['ByStr20.NombreTipo,'Uint128.TipoEntero],''bs1.Qid]]],
---     'opcionMatch__['true.Bool,'None`{_`}['Map__['ByStr20.NombreTipo,'Uint128.TipoEntero]]]]]]]]]],

---     '__['let__[
---     ''blk_leq.Qid,'funcion__['_:_[''blk1.Qid,'BNum.NombreTipo],'funcion__['_:_[''blk2.Qid,'BNum.NombreTipo],
---     'let__in_[''bc1.Qid,'builtin_['_<._[''blk1.Qid,''blk2.Qid]],'let__in_[''bc2.Qid,'builtin_['_==._[''blk1.Qid,
---     ''blk2.Qid]],'_or_[''bc1.Qid,''bc2.Qid]]]]]],
    
---     '__['let__[''accepted_code.Qid,'__['Int32.TipoEntero,'s_['0.Zero]]],
	
---     '__['let__[''missed_deadline_code.Qid,'__['Int32.TipoEntero,'s_^2['0.Zero]]],
	
--- 	'__['let__[
---     ''already_backed_code.Qid,'__['Int32.TipoEntero,'s_^3['0.Zero]]],'__['let__[''not_owner_code.Qid,'__[
---     'Int32.TipoEntero,'s_^4['0.Zero]]],'__['let__[''too_early_code.Qid,'__['Int32.TipoEntero,'s_^5['0.Zero]]],'__[
---     'let__[''got_funds_code.Qid,'__['Int32.TipoEntero,'s_^6['0.Zero]]],'__['let__[''cannot_get_funds.Qid,'__[
---     'Int32.TipoEntero,'s_^7['0.Zero]]],'__['let__[''cannot_reclaim_code.Qid,'__['Int32.TipoEntero,'s_^8['0.Zero]]],
---     'let__[''reclaimed_code.Qid,'__['Int32.TipoEntero,'s_^9['0.Zero]]]]]]]]]]]]]]],
	
    
---     'NombreContrato_[''Crowdfunding.Qid],
---     '_`,_['_:_[''owner.Qid,'ByStr20.NombreTipo],'_`,_['_:_[''max_block.Qid,'BNum.NombreTipo],
---     '_:_[''goal.Qid,'Uint128.TipoEntero]]],
    
---      '__['campo_=_['_:_[''backers.Qid,'Map__['ByStr20.NombreTipo,
---     'Uint128.TipoEntero]],'Emp__['ByStr20.NombreTipo,'Uint128.TipoEntero]],'campo_=_['_:_[''funded.Qid,
---     'Bool.NombreTipo],'false.Bool]],
    
---     '__['transicion___end[
---     ''Donate.Qid,'lpv.ListaParamInm,'__['_<-&BLOCKNUMBER[''blk.Qid],'__['_=_[''in_time.Qid,'aplicarF_['__[
---     ''blk_leq.Qid,''blk.Qid,''max_block.Qid]]],'match__[''in_time.Qid,'__['opcionMatch__['true.Bool,'__['guardar__[
---     ''bs.Qid,''backers.Qid],'__['_=_[''res.Qid,'aplicarF_['__[''check_update.Qid,''bs.Qid,''_sender.Qid,
---     ''_amount.Qid]]],'match__[''res.Qid,'__['opcionMatch__['None.Option,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_[
---     '"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,
---     ''already_backed_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[
---     ''msgs.Qid]]]],'opcionMatch__['Some_[''bs1.Qid],'__['actualizar__[''backers.Qid,''bs1.Qid],'__['accept.Declaracion,
---     '__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__[
---     'Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''accepted_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[
---     ''one_msg.Qid,''msg.Qid]]],'__['_=_[''e.Qid,'`{_;_`}['-eventname:_['"DonationAccepted".String],'_;_['_:_[
---     ''donor.Qid,''_sender.Qid],'_:_[''amount.Qid,''_amount.Qid]]]],'__['evento_[''e.Qid],'enviar_[
---     ''msgs.Qid]]]]]]]]]]]]],'opcionMatch__['false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[
---     ''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''missed_deadline_code.Qid]]],'__[
---     '_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]]]]]]],
    
---     '__[
---     'transicion___end[''GetFunds.Qid,'lpv.ListaParamInm,'__['_=_[''is_owner.Qid,'builtin_['_==._[''owner.Qid,
---     ''_sender.Qid]]],'match__[''is_owner.Qid,'__['opcionMatch__['false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_[
---     '"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,
---     ''not_owner_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[
---     ''msgs.Qid]]]],'opcionMatch__['true.Bool,'__['_<-&BLOCKNUMBER[''blk.Qid],'__['_=_[''in_time.Qid,'aplicarF_[
---     '__[''blk_leq.Qid,''blk.Qid,''max_block.Qid]]],'__['_=_[''c1.Qid,'negb_[''in_time.Qid]],'__['guardar__[''bal.Qid,
---     ''_balance.Qid],'__['_=_[''c2.Qid,'builtin_['_<._[''bal.Qid,''goal.Qid]]],'__['_=_[''c3.Qid,'negb_[''c2.Qid]],'__[
---     '_=_[''c4.Qid,'_and_[''c1.Qid,''c3.Qid]],'match__[''c4.Qid,'__['opcionMatch__['false.Bool,'__['_=_[''msg.Qid,
---     '`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[
---     ''code.Qid,''cannot_get_funds.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],
---     'enviar_[''msgs.Qid]]]],'opcionMatch__['true.Bool,'__['_=_[''tt.Qid,'true.Bool],'__['actualizar__[''funded.Qid,
---     ''tt.Qid],'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''owner.Qid],'cantidadEnvio_[''bal.Qid],
---     '_:_[''code.Qid,''got_funds_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],
---     'enviar_[''msgs.Qid]]]]]]]]]]]]]]]]]]]],
    
---     'transicion___end[''ClaimBack.Qid,'lpv.ListaParamInm,'__['_<-&BLOCKNUMBER[
---     ''blk.Qid],'__['_=_[''after_deadline.Qid,'builtin_['_<._[''max_block.Qid,''blk.Qid]]],'match__[''after_deadline.Qid,
---     '__['opcionMatch__['false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],
---     'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''too_early_code.Qid]]],'__['_=_[''msgs.Qid,
---     'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]],'opcionMatch__['true.Bool,'__[
---     'guardar__[''bs.Qid,''backers.Qid],'__['guardar__[''bal.Qid,''_balance.Qid],'__['guardar__[''f.Qid,''funded.Qid],
---     '__['_=_[''c1.Qid,'builtin_['_<._[''bal.Qid,''goal.Qid]]],'__['_=_[''c2.Qid,'builtin_['contains__[''bs.Qid,
---     ''_sender.Qid]]],'__['_=_[''c3.Qid,'negb_[''f.Qid]],'__['_=_[''c4.Qid,'_and_[''c1.Qid,''c2.Qid]],'__['_=_[''c5.Qid,
---     '_and_[''c3.Qid,''c4.Qid]],'match__[''c5.Qid,'__['opcionMatch__['false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}[
---     '-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,
---     ''cannot_reclaim_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[
---     ''msgs.Qid]]]],'opcionMatch__['true.Bool,'__['_=_[''res.Qid,'builtin_['get__[''bs.Qid,''_sender.Qid]]],'match__[
---     ''res.Qid,'__['opcionMatch__['None.Option,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[
---     ''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''cannot_reclaim_code.Qid]]],'__[
---     '_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]],'opcionMatch__['Some_[
---     ''v.Qid],'__['_=_[''bs1.Qid,'builtin_['remove__[''bs.Qid,''_sender.Qid]]],'__['actualizar__[''backers.Qid,
---     ''bs1.Qid],'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_[''v.Qid],
---     '_:_[''code.Qid,''reclaimed_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'__[
---     '_=_[''e.Qid,'`{_;_`}['-eventname:_['"ClaimedBack".String],'_;_['_:_[''claimed_by.Qid,''_sender.Qid],'_:_[
---     ''amount.Qid,''v.Qid]]]],'__['evento_[''e.Qid],'enviar_[''msgs.Qid]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]],'mv.Memoria,'mv.Memoria], unbounded) .





--- ***Contrato4
--- red metaRewrite(upModule('REGLAS, true), '`[_`,_`,_`]['Contrato_______['0.Zero,'import_['BoolUtils.LibImportar],'__['NombreLibreria_[''OpenAuction.Qid],'__[
---     'let__[''blk_leq.Qid,'funcion__['_:_[''blk1.Qid,'BNum.NombreTipo],'funcion__['_:_[''blk2.Qid,'BNum.NombreTipo],
---     'let__in_[''bc1.Qid,'builtin_['_<._[''blk1.Qid,''blk2.Qid]],'let__in_[''bc2.Qid,'builtin_['_==._[''blk1.Qid,
---     ''blk2.Qid]],'_or_[''bc1.Qid,''bc2.Qid]]]]]],
    
---     '__['let__[''one_msg.Qid,'funcion__['_:_[''msg.Qid,
---     'Message.NombreTipo],'let__in_[''nil_msg.Qid,'Nil`{_`}['Message.NombreTipo],'Cons___['Message.NombreTipo,
---     ''msg.Qid,''nil_msg.Qid]]]],
    
---     '__['let__[''late_to_bid_code.Qid,'__['Int32.TipoEntero,'s_['0.Zero]]],'__['let__[
---     ''too_early_to_bid_code.Qid,'__['Int32.TipoEntero,'s_^2['0.Zero]]],'__['let__[''bid_too_low_code.Qid,'__[
---     'Int32.TipoEntero,'s_^3['0.Zero]]],'__['let__[''first_bid_accepted_code.Qid,'__['Int32.TipoEntero,'s_^4['0.Zero]]],
---     '__['let__[''bid_accepted_code.Qid,'__['Int32.TipoEntero,'s_^5['0.Zero]]],'__['let__[''money_sent_code.Qid,'__[
---     'Int32.TipoEntero,'s_^6['0.Zero]]],'__['let__[''nothing_to_withdraw_code.Qid,'__['Int32.TipoEntero,'s_^7[
---     '0.Zero]]],'__['let__[''auction_is_still_on_code.Qid,'__['Int32.TipoEntero,'s_^8['0.Zero]]],'let__[
---     ''auction_end_code.Qid,'__['Int32.TipoEntero,'s_^9['0.Zero]]]]]]]]]]]]]],
    
---     'NombreContrato_[''OpenAuction.Qid],
    
---     '_`,_[
---     '_:_[''auctionStart.Qid,'BNum.NombreTipo],'_`,_['_:_[''biddingTime.Qid,'Uint128.TipoEntero],'_:_[''beneficiary.Qid,
---     'ByStr20.NombreTipo]]],
    
---     '__['campo_=_['_:_[''ended.Qid,'Bool.NombreTipo],'false.Bool],'__['campo_=_['_:_[
---     ''highestBidder.Qid,'Option_['ByStr20.NombreTipo]],'None`{_`}['ByStr20.NombreTipo]],'__['campo_=_['_:_[
---     ''highestBid.Qid,'Uint128.TipoEntero],'__['Uint128.TipoEntero,'0.Zero]],'campo_=_['_:_[''pendingReturns.Qid,'Map__[
---     'ByStr20.NombreTipo,'Uint128.TipoEntero]],'Emp__['ByStr20.NombreTipo,'Uint128.TipoEntero]]]]],
    
---     '__[
---     'transicion___end[''Bid.Qid,'lpv.ListaParamInm,'__['_<-&BLOCKNUMBER[''blk.Qid],'__['_=_[''endtime.Qid,'builtin_[
---     '_+._[''auctionStart.Qid,''biddingTime.Qid]]], '__['_=_[''after_end.Qid,'let__in_[''one.Qid,'__['Uint128.TipoEntero,
---     's_['0.Zero]],'builtin_['_+._[''endtime.Qid,''one.Qid]]]], '__['guardar__[''e.Qid,''ended.Qid],'__['_=_[
---     ''in_time.Qid,'aplicarF_['__[''blk_leq.Qid,''after_end.Qid,''blk.Qid]]],'__['_=_[''flag1.Qid,'_or_[
---     ''in_time.Qid,''e.Qid]],'__['_=_[''early.Qid,'aplicarF_['__[''blk_leq.Qid,''blk.Qid,''auctionStart.Qid]]],
---     'match__[''early.Qid,'__['opcionMatch__['true.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[
---     ''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''too_early_to_bid_code.Qid]]],
---     '__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]],'opcionMatch__[
---     'false.Bool,'match__[''flag1.Qid,'__['opcionMatch__['true.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],
---     'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,
---     ''late_to_bid_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[
---     ''msgs.Qid]]]],'opcionMatch__['false.Bool,'__['guardar__[''hb.Qid,''highestBid.Qid],'__['_=_[''sufficientBid.Qid,
---     'builtin_['_<._[''hb.Qid,''_amount.Qid]]],'match__[''sufficientBid.Qid,'__['opcionMatch__['false.Bool,'__['_=_[
---     ''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,
---     '0.Zero]],'_:_[''code.Qid,''bid_too_low_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,
---     ''msg.Qid]]],'enviar_[''msgs.Qid]]]],'opcionMatch__['true.Bool,'__['accept.Declaracion,'__['guardar__[
---     ''hbPrev.Qid,''highestBidder.Qid],'match__[''hbPrev.Qid,'__['opcionMatch__['Some_[''prevHighestBidder.Qid],'__[
---     'obtener___[''option_pendingReturnsForPrevHB.Qid,''pendingReturns.Qid,'posicion_[''prevHighestBidder.Qid]],'__[
---     '_=_[''getPRForPrevHighestBidder.Qid,'match__[''option_pendingReturnsForPrevHB.Qid,'__['opcionMatch__['Some_[
---     ''pendingReturnsForPrevHB.Qid],'builtin_['_+._[''hb.Qid,''pendingReturnsForPrevHB.Qid]]],'opcionMatch__[
---     'None.Option,''hb.Qid]]]],'__['insertar___[''pendingReturns.Qid,'posicion_[''prevHighestBidder.Qid],
---     ''getPRForPrevHighestBidder.Qid],'__['_=_[''bidder.Qid,'Some__['ByStr20.NombreTipo,''_sender.Qid]],'__[
---     'actualizar__[''highestBidder.Qid,''bidder.Qid],'__['actualizar__[''highestBid.Qid,''_amount.Qid],'__['_=_[''e.Qid,
---     '`{_;_`}['-eventname:_['"Bid".String],'_;_['_:_[''code.Qid,''bid_accepted_code.Qid],'_;_['_:_[''addr.Qid,
---     ''_sender.Qid],'_:_[''amount.Qid,''_amount.Qid]]]]],'evento_[''e.Qid]]]]]]]]],'opcionMatch__['None.Option,'__['_=_[
---     ''first_bidder.Qid,'Some__['ByStr20.NombreTipo,''_sender.Qid]],'__['actualizar__[''highestBidder.Qid,
---     ''first_bidder.Qid],'__['actualizar__[''highestBid.Qid,''_amount.Qid],'__['_=_[''e.Qid,'`{_;_`}['-eventname:_[
---     '"Bid".String],'_;_['_:_[''code.Qid,''first_bid_accepted_code.Qid],'_;_['_:_[''addr.Qid,''_sender.Qid],'_:_[
---     ''amount.Qid,''_amount.Qid]]]]],'evento_[''e.Qid]]]]]]]]]]]]]]]]]]]]]]]]]]]]],
    
---     '__['transicion___end[''Withdraw.Qid,
---     'lpv.ListaParamInm,'__['guardar__[''prs.Qid,''pendingReturns.Qid],'__['_=_[''pr.Qid,'builtin_['get__[''prs.Qid,
---     ''_sender.Qid]]],'match__[''pr.Qid,'__['opcionMatch__['None.Option,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_[
---     '"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,
---     ''nothing_to_withdraw_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[
---     ''msgs.Qid]]]],'opcionMatch__['Some_[''v.Qid],'__['delete__[''pendingReturns.Qid,'posicion_[''_sender.Qid]],'__[
---     '_=_[''e.Qid,'`{_;_`}['-eventname:_['"Withdraw Successful".String],'_:_[''addr.Qid,''_sender.Qid]]],'__['evento_[
---     ''e.Qid],'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_[''v.Qid],
---     '_:_[''code.Qid,''money_sent_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],
---     'enviar_[''msgs.Qid]]]]]]]]]]]],
    
---     'transicion___end[''AuctionEnd.Qid,'lpv.ListaParamInm,'__['_<-&BLOCKNUMBER[
---     ''blk.Qid],'__['guardar__[''e.Qid,''ended.Qid],'__['_=_[''t1.Qid,'builtin_['_+._[''auctionStart.Qid,
---     ''biddingTime.Qid]]],'__['_=_[''t2.Qid,'aplicarF_['__[''blk_leq.Qid,''t1.Qid,''blk.Qid]]],'__['_=_[
---     ''t3.Qid,'negb_[''e.Qid]],'__['_=_[''t4.Qid,'_and_[''t2.Qid,''t3.Qid]],'match__[''t4.Qid,'__['opcionMatch__[
---     'false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__[
---     'Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''auction_is_still_on_code.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_[
---     '__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]],'opcionMatch__['true.Bool,'__['_=_[''val.Qid,
---     'true.Bool],'__['actualizar__[''ended.Qid,''val.Qid],'__['guardar__[''hb.Qid,''highestBid.Qid],'__['_=_[''e.Qid,
---     '`{_;_`}['-eventname:_['"Auction ended".String],'_:_[''highest_bid.Qid,''hb.Qid]]],'__['evento_[''e.Qid],'__['_=_[
---     ''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''beneficiary.Qid],'cantidadEnvio_[''hb.Qid],'_;_['_:_[
---     ''code.Qid,''auction_end_code.Qid],'_:_[''highest_bid.Qid,''hb.Qid]]]],'__['_=_[''msgs.Qid,'aplicarF_['__[
---     ''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]]]]]]]]]]]]]]]]]]]    
--- ,'mv.Memoria,'mv.Memoria], unbounded) .

--- ***Ejecutar transicion 1 (no funciona del todo)
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['Importaciones`[_`]['BoolUtils.LibImportar],'`[_=>_`][''auctionStart.Qid,
---     's_^2['0.Zero]],'`[_=>_`][''biddingTime.Qid,'s_^2['0.Zero]],'`[_=>_`][''beneficiary.Qid,
---     'ByStr20.NombreTipo],'`[_=>_`][''ended.Qid,'false.Bool],'`[_=>_`][''blk_leq.Qid,'Funcion`[_`,_`]['`[_=>_`][
---     ''blk1.Qid,'BNum.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''blk2.Qid,'BNum.NombreTipo],'`[_=>_`,_`][''bc1.Qid,'`[_`][
---     '_<._[''blk1.Qid,''blk2.Qid]],'`[_=>_`,_`][''bc2.Qid,'`[_`]['_==._[''blk1.Qid,''blk2.Qid]],'`[_`]['_or_[''bc1.Qid,
---     ''bc2.Qid]]]]]]],'`[_=>_`][''highestBidder.Qid,'None.Option],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][
---     ''msg.Qid,'Message.NombreTipo],'`[_=>_`,_`][''nil_msg.Qid,'Nil`[_`]['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,
---     ''nil_msg.Qid]]]],'`[_=>_`][''highestBid.Qid,'0.Zero],'`[_=>_`][''late_to_bid_code.Qid,'s_['0.Zero]],'`[_=>_`][
---     ''pendingReturns.Qid,'empty.Map`{Nat`,Clave`}],'`[_=>_`][''too_early_to_bid_code.Qid,'s_^2['0.Zero]],'`[_=>_`][
---     ''bid_too_low_code.Qid,'s_^3['0.Zero]],'`[_=>_`][''first_bid_accepted_code.Qid,'s_^4['0.Zero]],'`[_=>_`][
---     ''bid_accepted_code.Qid,'s_^5['0.Zero]],'`[_=>_`][''money_sent_code.Qid,'s_^6['0.Zero]],'`[_=>_`][
---     ''nothing_to_withdraw_code.Qid,'s_^7['0.Zero]],'`[_=>_`][''auction_is_still_on_code.Qid,'s_^8['0.Zero]],'`[_=>_`][
---     ''auction_end_code.Qid,'s_^9['0.Zero]]],
---     '`[_`,_`,_`,_`,_`][''Bid.Qid,'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['NumBloque`[_`][''blk.Qid],'`[_=>_`][
---     ''endtime.Qid,'`[_`]['_+._[''auctionStart.Qid,''biddingTime.Qid]]],'`[_=>_`][''after_end.Qid,'`[_=>_`,_`][
---     ''one.Qid,'s_['0.Zero],'`[_`]['_+._[''endtime.Qid,''one.Qid]]]],'`[_=>_`][''e.Qid,''ended.Qid],'`[_=>_`][
---     ''in_time.Qid,'AplicarF`[_`,_`][''blk_leq.Qid,'__[''after_end.Qid,''blk.Qid]]],'`[_=>_`][''flag1.Qid,'`[_`]['_or_[
---     ''in_time.Qid,''e.Qid]]],'`[_=>_`][''early.Qid,'AplicarF`[_`,_`][''blk_leq.Qid,'__[''blk.Qid,''auctionStart.Qid]]],
---     '`[_=>_`][''early.Qid,'__['`[_=>_`]['true.Bool,'__['`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],
---     '`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,
---     ''too_early_to_bid_code.Qid]]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][
---     ''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['false.Bool,'`[_=>_`][''flag1.Qid,'__['`[_=>_`]['true.Bool,'__['`[_=>_`][
---     ''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][
---     ''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''late_to_bid_code.Qid]]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][
---     ''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['false.Bool,'__['`[_=>_`][''hb.Qid,
---     ''highestBid.Qid],'`[_=>_`][''sufficientBid.Qid,'`[_`]['_<._[''hb.Qid,''_amount.Qid]]],'`[_=>_`][
---     ''sufficientBid.Qid,'__['`[_=>_`]['false.Bool,'__['`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],
---     '`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,
---     ''bid_too_low_code.Qid]]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,
---     ''msgs.Qid]]],'`[_=>_`]['true.Bool,'__['`[_`]['accept.Declaracion],'`[_=>_`][''hbPrev.Qid,''highestBidder.Qid],
---     '`[_=>_`][''hbPrev.Qid,'__['`[_=>_`]['Some_[''prevHighestBidder.Qid],'__['Obtener`[_=>_`,_`][
---     ''option_pendingReturnsForPrevHB.Qid,''pendingReturns.Qid,'posicion_[''prevHighestBidder.Qid]],'`[_=>_`][
---     ''getPRForPrevHighestBidder.Qid,'`[_=>_`][''option_pendingReturnsForPrevHB.Qid,'__['`[_=>_`]['Some_[
---     ''pendingReturnsForPrevHB.Qid],'`[_`]['_+._[''hb.Qid,''pendingReturnsForPrevHB.Qid]]],'`[_=>_`]['None.Option,
---     ''hb.Qid]]]],'Insertar`[_=>_`,_`][''pendingReturns.Qid,''getPRForPrevHighestBidder.Qid,'posicion_[
---     ''prevHighestBidder.Qid]],'`[_=>_`][''bidder.Qid,'Some`[_`][''_sender.Qid]],'Actualizar`[_`,_`][
---     ''highestBidder.Qid,''bidder.Qid],'Actualizar`[_`,_`][''highestBid.Qid,''_amount.Qid],'`[_=>_`][''e.Qid,'__[
---     '`[_=>_`][''eventname.Qid,'"Bid".String],'`[_=>_`][''code.Qid,''bid_accepted_code.Qid],'`[_=>_`][''addr.Qid,
---     ''_sender.Qid],'`[_=>_`][''amount.Qid,''_amount.Qid]]],'`[_=>_`][''evento.Qid,''e.Qid]]],'`[_=>_`]['None.Option,
---     '__['`[_=>_`][''first_bidder.Qid,'Some`[_`][''_sender.Qid]],'Actualizar`[_`,_`][''highestBidder.Qid,
---     ''first_bidder.Qid],'Actualizar`[_`,_`][''highestBid.Qid,''_amount.Qid],'`[_=>_`][''e.Qid,'__['`[_=>_`][
---     ''eventname.Qid,'"Bid".String],'`[_=>_`][''code.Qid,''first_bid_accepted_code.Qid],'`[_=>_`][''addr.Qid,
---     ''_sender.Qid],'`[_=>_`][''amount.Qid,''_amount.Qid]]],'`[_=>_`][''evento.Qid,''e.Qid]]]]]]]]]]]]]]]]],'__[
---     '`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,'ByStr20.NombreTipo]]]], unbounded) .
--- ***Ejecutar transicion 2
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['Importaciones`[_`]['BoolUtils.LibImportar],'`[_=>_`][''auctionStart.Qid,
---     'BNum.NombreTipo],'`[_=>_`][''biddingTime.Qid,'Uint128.TipoEntero],'`[_=>_`][''beneficiary.Qid,
---     'ByStr20.NombreTipo],'`[_=>_`][''ended.Qid,'false.Bool],'`[_=>_`][''blk_leq.Qid,'Funcion`[_`,_`]['`[_=>_`][
---     ''blk1.Qid,'BNum.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''blk2.Qid,'BNum.NombreTipo],'`[_=>_`,_`][''bc1.Qid,'`[_`][
---     '_<._[''blk1.Qid,''blk2.Qid]],'`[_=>_`,_`][''bc2.Qid,'`[_`]['_==._[''blk1.Qid,''blk2.Qid]],'`[_`]['_or_[''bc1.Qid,
---     ''bc2.Qid]]]]]]],'`[_=>_`][''highestBidder.Qid,'None.Option],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][
---     ''msg.Qid,'Message.NombreTipo],'`[_=>_`,_`][''nil_msg.Qid,'Nil`[_`]['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,
---     ''nil_msg.Qid]]]],'`[_=>_`][''highestBid.Qid,'0.Zero],'`[_=>_`][''late_to_bid_code.Qid,'s_['0.Zero]],'`[_=>_`][
---     ''pendingReturns.Qid,'_|->_['s_^2['0.Zero],'s_^4['0.Zero]]],'`[_=>_`][''too_early_to_bid_code.Qid,'s_^2['0.Zero]],'`[_=>_`][
---     ''bid_too_low_code.Qid,'s_^3['0.Zero]],'`[_=>_`][''first_bid_accepted_code.Qid,'s_^4['0.Zero]],'`[_=>_`][
---     ''bid_accepted_code.Qid,'s_^5['0.Zero]],'`[_=>_`][''money_sent_code.Qid,'s_^6['0.Zero]],'`[_=>_`][
---     ''nothing_to_withdraw_code.Qid,'s_^7['0.Zero]],'`[_=>_`][''auction_is_still_on_code.Qid,'s_^8['0.Zero]],'`[_=>_`][
---     ''auction_end_code.Qid,'s_^9['0.Zero]]],'`[_`,_`,_`,_`,_`][
---     ''Withdraw.Qid,'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['`[_=>_`][''prs.Qid,''pendingReturns.Qid],'`[_=>_`][
---     ''pr.Qid,'`[_`]['get__[''prs.Qid,''_sender.Qid]]],'`[_=>_`][''pr.Qid,'__['`[_=>_`]['None.Option,'__['`[_=>_`][
---     ''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][
---     ''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''nothing_to_withdraw_code.Qid]]],'`[_=>_`][''msgs.Qid,
---     'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['Some_[''v.Qid],'__[
---     'Eliminar`[_`,_`][''pendingReturns.Qid,'posicion_[''_sender.Qid]],'`[_=>_`][''e.Qid,'__['`[_=>_`][''eventname.Qid,
---     '"Withdraw Successful".String],'`[_=>_`][''addr.Qid,''_sender.Qid]]],'`[_=>_`][''evento.Qid,''e.Qid],'`[_=>_`][
---     ''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][
---     ''cantidadEnvio.Qid,''v.Qid],'`[_=>_`][''code.Qid,''money_sent_code.Qid]]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][
---     ''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]]]]],'__['`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],
---     '`[_=>_`][''_sender.Qid,'s_^2['0.Zero]]]]], unbounded) .
--- ***Ejecutar transicion 3 (solucionar problema de las variables repetidas y aplicar la funcion)
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['Importaciones`[_`]['BoolUtils.LibImportar],'`[_=>_`][''auctionStart.Qid,
---     's_^2['0.Zero]],'`[_=>_`][''biddingTime.Qid,'s_^2['0.Zero]],'`[_=>_`][''beneficiary.Qid,
---     's_^9['0.Zero]],'`[_=>_`][''ended.Qid,'false.Bool],'`[_=>_`][''blk_leq.Qid,'Funcion`[_`,_`]['`[_=>_`][
---     ''blk1.Qid,'BNum.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''blk2.Qid,'BNum.NombreTipo],'`[_=>_`,_`][''bc1.Qid,'`[_`][
---     '_<._[''blk1.Qid,''blk2.Qid]],'`[_=>_`,_`][''bc2.Qid,'`[_`]['_==._[''blk1.Qid,''blk2.Qid]],'`[_`]['_or_[''bc1.Qid,
---     ''bc2.Qid]]]]]]],'`[_=>_`][''highestBidder.Qid,'None.Option],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][
---     ''msg.Qid,'Message.NombreTipo],'`[_=>_`,_`][''nil_msg.Qid,'Nil`[_`]['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,
---     ''nil_msg.Qid]]]],'`[_=>_`][''highestBid.Qid,'0.Zero],'`[_=>_`][''late_to_bid_code.Qid,'s_['0.Zero]],'`[_=>_`][
---     ''pendingReturns.Qid,'empty.Map`{Nat`,Clave`}],'`[_=>_`][''too_early_to_bid_code.Qid,'s_^2['0.Zero]],'`[_=>_`][
---     ''bid_too_low_code.Qid,'s_^3['0.Zero]],'`[_=>_`][''first_bid_accepted_code.Qid,'s_^4['0.Zero]],'`[_=>_`][
---     ''bid_accepted_code.Qid,'s_^5['0.Zero]],'`[_=>_`][''money_sent_code.Qid,'s_^6['0.Zero]],'`[_=>_`][
---     ''nothing_to_withdraw_code.Qid,'s_^7['0.Zero]],'`[_=>_`][''auction_is_still_on_code.Qid,'s_^8['0.Zero]],'`[_=>_`][
---     ''auction_end_code.Qid,'s_^9['0.Zero]]],'`[_`,_`,_`,_`,_`][''AuctionEnd.Qid,'lpv.ListaParamInm,
---     'ldv.ListaDeclaraciones,'__['NumBloque`[_`][''blk.Qid],'`[_=>_`][''e.Qid,''ended.Qid],'`[_=>_`][''t1.Qid,'`[_`][
---     '_+._[''auctionStart.Qid,''biddingTime.Qid]]],'`[_=>_`][''t2.Qid,'AplicarF`[_`,_`][''blk_leq.Qid,'__[''t1.Qid,
---     ''blk.Qid]]],'`[_=>_`][''t3.Qid,'`[_`]['negb_[''e.Qid]]],'`[_=>_`][''t4.Qid,'`[_`]['_and_[''t2.Qid,''t3.Qid]]],
---     '`[_=>_`][''t4.Qid,'__['`[_=>_`]['false.Bool,'__['`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][
---     ''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,
---     ''auction_is_still_on_code.Qid]]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][
---     ''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['true.Bool,'__['`[_=>_`][''val.Qid,'`[_`]['true.Bool]],'Actualizar`[_`,_`][
---     ''ended.Qid,''val.Qid],'`[_=>_`][''hb.Qid,''highestBid.Qid],'`[_=>_`][''e.Qid,'__['`[_=>_`][''eventname.Qid,
---     '"Auction ended".String],'`[_=>_`][''highest_bid.Qid,''hb.Qid]]],'`[_=>_`][''evento.Qid,''e.Qid],'`[_=>_`][
---     ''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''beneficiary.Qid],'`[_=>_`][
---     ''cantidadEnvio.Qid,''hb.Qid],'`[_=>_`][''code.Qid,''auction_end_code.Qid],'`[_=>_`][''highest_bid.Qid,''hb.Qid]]],
---     '`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]]]]],'__[
---     '`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,'s_^2['0.Zero]]]]], unbounded) .


--- ***Contrato5
--- red metaRewrite(upModule('REGLAS, true), '`[_`,_`,_`]['Contrato_______['0.Zero,'import_['IntUtils.LibImportar],'__['NombreLibreria_[''FungibleToken.Qid],
--- '__[
---     'let__[''one_msg.Qid,'funcion__['_:_[''msg.Qid,'Message.NombreTipo],'let__in_[''nil_msg.Qid,'Nil`{_`}[
---     'Message.NombreTipo],'Cons___['Message.NombreTipo,''msg.Qid,''nil_msg.Qid]]]],
    
---     '__['let__[''two_msgs.Qid,
---     'funcion__['_:_[''msg1.Qid,'Message.NombreTipo],'funcion__['_:_[''msg2.Qid,'Message.NombreTipo],'let__in_[
---     ''msgs_tmp.Qid,'aplicarF_['__[''one_msg.Qid,''msg2.Qid]],'Cons___['Message.NombreTipo,''msg1.Qid,
---     ''msgs_tmp.Qid]]]]],
    
---     '__['tipo__[''Error.Qid,'__['|_[''CodeIsSender.Qid],'__['|_[''CodeInsufficientFunds.Qid],'|_[
---     ''CodeInsufficientAllowance.Qid]]]],
    
---     '__['let__[''make_error.Qid,'funcion__['_:_[''result.Qid,'Error.NombreTipo],
---     'let__in_[''result_code.Qid,'match__[''result.Qid,'__['opcionMatch__[''CodeIsSender.Qid,'__[
---     'Int32.TipoEntero,'-_['s_['0.Zero]]]],'__['opcionMatch__[''CodeInsufficientFunds.Qid,'__[
---     'Int32.TipoEntero,'-_['s_^2['0.Zero]]]],'opcionMatch__[''CodeInsufficientAllowance.Qid,'__[
---     'Int32.TipoEntero,'-_['s_^3['0.Zero]]]]]]],'`{_;_`}['-exception:_['"Error".String],'_:_[''code.Qid,
---     ''result_code.Qid]]]]],
    
---     '__['let__[''zero.Qid,'__['Uint128.TipoEntero,'0.Zero]],
    
---     '__['tipo__[''Unit.Qid,'|_[
---     ''Unit.Qid]],
    
---     'let__[''get_val.Qid,'funcion__['_:_[''some_val.Qid,'Option_['Uint128.TipoEntero]],'match__[
---     ''some_val.Qid,'__['opcionMatch__['Some_[''val.Qid],''val.Qid],'opcionMatch__['None.Option,
---     ''zero.Qid]]]]]]]]]]]],
    
---     'NombreContrato_[''FungibleToken.Qid],
    
---     '_`,_['_:_[''contract_owner.Qid,'ByStr20.NombreTipo],
---     '_`,_['_:_[''name.Qid,'String.NombreTipo],'_`,_['_:_[''symbol.Qid,'String.NombreTipo],'_`,_['_:_[''decimals.Qid,
---     'Uint32.TipoEntero],'_:_[''init_supply.Qid,'Uint128.TipoEntero]]]]],
    
---     '__['campo_=_['_:_[''total_supply.Qid,
---     'Uint128.TipoEntero],'aplicarF_[''init_supply.Qid]],'__['campo_=_['_:_[''balances.Qid,'Map__[
---     'ByStr20.NombreTipo,'Uint128.TipoEntero]],'let__in_[''emp_map.Qid,'Emp__['ByStr20.NombreTipo,'Uint128.TipoEntero],
---     'builtin_['put___[''emp_map.Qid,''contract_owner.Qid,''init_supply.Qid]]]],'campo_=_['_:_[''allowances.Qid,'Map__[
---     'ByStr20.NombreTipo,'Map__['ByStr20.NombreTipo,'Uint128.TipoEntero]]],'Emp__['ByStr20.NombreTipo,'Map__[
---     'ByStr20.NombreTipo,'Uint128.TipoEntero]]]]],
    
---     '__['procedimiento___end[''ThrowError.Qid,'_:_[''err.Qid,
---     'Error.NombreTipo],'__['_=_[''e.Qid,'aplicarF_['__[''make_error.Qid,''err.Qid]]],'throw_[
---     ''e.Qid]]],
    
---     '__['procedimiento___end[''IsNotSender.Qid,'_:_[''address.Qid,'ByStr20.NombreTipo],'__['_=_[
---     ''is_sender.Qid,'builtin_['_==._[''_sender.Qid,''address.Qid]]],'match__[''is_sender.Qid,'__['opcionMatch__[
---     'true.Bool,'__['_=_[''err.Qid,'aplicarF_[''CodeIsSender.Qid]],'aplicarF_['__[''ThrowError.Qid,
---     ''err.Qid]]]],'opcionMatch__['false.Bool,'ev.Expresiones]]]]],
    
---     '__['procedimiento___end[
---     ''AuthorizedMoveIfSufficientBalance.Qid,'_`,_['_:_[''from.Qid,'ByStr20.NombreTipo],'_`,_['_:_[''to.Qid,
---     'ByStr20.NombreTipo],'_:_[''amount.Qid,'Uint128.TipoEntero]]],'__['obtener___[''o_from_bal.Qid,''balances.Qid,
---     'posicion_[''from.Qid]],'__['_=_[''bal.Qid,'aplicarF_['__[''get_val.Qid,''o_from_bal.Qid]]],'__['_=_[
---     ''can_do.Qid,'aplicarF_['__[''uint128_le.Qid,''amount.Qid,''bal.Qid]]],'match__[''can_do.Qid,'__[
---     'opcionMatch__['true.Bool,'__['_=_[''new_from_bal.Qid,'builtin_['_-_[''bal.Qid,''amount.Qid]]],'__['insertar___[
---     ''balances.Qid,'posicion_[''from.Qid],''new_from_bal.Qid],'__['obtener___[''get_to_bal.Qid,''balances.Qid,
---     'posicion_[''to.Qid]],'__['_=_[''new_to_bal.Qid,'match__[''get_to_bal.Qid,'__['opcionMatch__['Some_[''bal.Qid],
---     'builtin_['_+._[''bal.Qid,''amount.Qid]]],'opcionMatch__['None.Option,''amount.Qid]]]],'insertar___[
---     ''balances.Qid,'posicion_[''to.Qid],''new_to_bal.Qid]]]]]],'opcionMatch__['false.Bool,'__['_=_[''err.Qid,
---     'aplicarF_[''CodeInsufficientFunds.Qid]],'aplicarF_['__[''ThrowError.Qid,''err.Qid]]]]]]]]]],
    
---     '__[
---     'transicion___end[''IncreaseAllowance.Qid,'_`,_['_:_[''spender.Qid,'ByStr20.NombreTipo],'_:_[''amount.Qid,
---     'Uint128.TipoEntero]],'__['aplicarF_['__[''IsNotSender.Qid,''spender.Qid]],'__['obtener___[
---     ''some_current_allowance.Qid,''allowances.Qid,'__['posicion_[''_sender.Qid],'posicion_[''spender.Qid]]],'__['_=_[
---     ''current_allowance.Qid,'aplicarF_['__[''get_val.Qid,''some_current_allowance.Qid]]],'__['_=_[
---     ''new_allowance.Qid,'builtin_['_+._[''current_allowance.Qid,''amount.Qid]]],'__['insertar___[''allowances.Qid,'__[
---     'posicion_[''_sender.Qid],'posicion_[''spender.Qid]],''new_allowance.Qid],'__['_=_[''e.Qid,'`{_;_`}['-eventname:_[
---     '"IncreasedAllowance".String],'_;_['_:_[''token_owner.Qid,''_sender.Qid],'_;_['_:_[''spender.Qid,''spender.Qid],
---     '_:_[''new_allowance.Qid,''new_allowance.Qid]]]]],'evento_[''e.Qid]]]]]]]],
    
---     '__['transicion___end[
---     ''DecreaseAllowance.Qid,'_`,_['_:_[''spender.Qid,'ByStr20.NombreTipo],'_:_[''amount.Qid,'Uint128.TipoEntero]],'__[
---     'aplicarF_['__[''IsNotSender.Qid,''spender.Qid]],'__['obtener___[''some_current_allowance.Qid,
---     ''allowances.Qid,'__['posicion_[''_sender.Qid],'posicion_[''spender.Qid]]],'__['_=_[''current_allowance.Qid,
---     'aplicarF_['__[''get_val.Qid,''some_current_allowance.Qid]]],'__['_=_[''new_allowance.Qid,'let__in_[
---     ''amount_le_allowance.Qid,'aplicarF_['__[''uint128_le.Qid,''amount.Qid,''current_allowance.Qid]],'match__[
---     ''amount_le_allowance.Qid,'__['opcionMatch__['true.Bool,'builtin_['_-_[''current_allowance.Qid,''amount.Qid]]],
---     'opcionMatch__['false.Bool,''zero.Qid]]]]],'__['insertar___[''allowances.Qid,'__['posicion_[
---     ''_sender.Qid],'posicion_[''spender.Qid]],''new_allowance.Qid],'__['_=_[''e.Qid,'`{_;_`}['-eventname:_[
---     '"DecreasedAllowance".String],'_;_['_:_[''token_owner.Qid,''_sender.Qid],'_;_['_:_[''spender.Qid,''spender.Qid],
---     '_:_[''new_allowance.Qid,''new_allowance.Qid]]]]],'evento_[''e.Qid]]]]]]]],
    
---     '__['transicion___end[''Transfer.Qid,
---     '_`,_['_:_[''to.Qid,'ByStr20.NombreTipo],'_:_[''amount.Qid,'Uint128.TipoEntero]],'__['aplicarF_['__[
---     ''AuthorizedMoveIfSufficientBalance.Qid,''_sender.Qid,''to.Qid,''amount.Qid]],'__['_=_[''e.Qid,'`{_;_`}[
---     '-eventname:_['"TransferSuccess".String],'_;_['_:_[''sender.Qid,''_sender.Qid],'_;_['_:_[''recipient.Qid,''to.Qid],
---     '_:_[''amount.Qid,''amount.Qid]]]]],'__['evento_[''e.Qid],'__['_=_[''msg_to_recipient.Qid,'`{_;_;_;_`}['-tag:_[
---     '"RecipientAcceptTransfer".String],'dirEnvio_[''to.Qid],'cantidadEnvio_[''zero.Qid],'_;_['_:_[''sender.Qid,
---     ''_sender.Qid],'_;_['_:_[''recipient.Qid,''to.Qid],'_:_[''amount.Qid,''amount.Qid]]]]],'__['_=_[
---     ''msg_to_sender.Qid,'`{_;_;_;_`}['-tag:_['"TransferSuccessCallBack".String],'dirEnvio_[''_sender.Qid],
---     'cantidadEnvio_[''zero.Qid],'_;_['_:_[''sender.Qid,''_sender.Qid],'_;_['_:_[''recipient.Qid,''to.Qid],'_:_[
---     ''amount.Qid,''amount.Qid]]]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''two_msgs.Qid,''msg_to_recipient.Qid,
---     ''msg_to_sender.Qid]]],'enviar_[''msgs.Qid]]]]]]]],
    
---     'transicion___end[''TransferFrom.Qid,'_`,_['_:_[''from.Qid,
---     'ByStr20.NombreTipo],'_`,_['_:_[''to.Qid,'ByStr20.NombreTipo],'_:_[''amount.Qid,'Uint128.TipoEntero]]],'__[
---     'obtener___[''o_spender_allowed.Qid,''allowances.Qid,'__['posicion_[''from.Qid],'posicion_[''_sender.Qid]]],'__[
---     '_=_[''allowed.Qid,'aplicarF_['__[''get_val.Qid,''o_spender_allowed.Qid]]],'__['_=_[''can_do.Qid,
---     'aplicarF_['__[''uint128_le.Qid,''amount.Qid,''allowed.Qid]]],'match__[''can_do.Qid,'__['opcionMatch__[
---     'true.Bool,'__['aplicarF_['__[''AuthorizedMoveIfSufficientBalance.Qid,''from.Qid,''to.Qid,''amount.Qid]],
---     '__['_=_[''e.Qid,'`{_;_`}['-eventname:_['"TransferFromSuccess".String],'_;_['_:_[''initiator.Qid,''_sender.Qid],
---     '_;_['_:_[''sender.Qid,''from.Qid],'_;_['_:_[''recipient.Qid,''to.Qid],'_:_[''amount.Qid,''amount.Qid]]]]]],'__[
---     'evento_[''e.Qid],'__['_=_[''new_allowed.Qid,'builtin_['_-_[''allowed.Qid,''amount.Qid]]],'__['insertar___[
---     ''allowances.Qid,'__['posicion_[''from.Qid],'posicion_[''_sender.Qid]],''new_allowed.Qid],'__['_=_[
---     ''msg_to_recipient.Qid,'`{_;_;_;_`}['-tag:_['"RecipientAcceptTransferFrom".String],'dirEnvio_[''to.Qid],
---     'cantidadEnvio_[''zero.Qid],'_;_['_:_[''initiator.Qid,''_sender.Qid],'_;_['_:_[''sender.Qid,''from.Qid],'_;_['_:_[
---     ''recipient.Qid,''to.Qid],'_:_[''amount.Qid,''amount.Qid]]]]]],'__['_=_[''msg_to_sender.Qid,'`{_;_;_;_`}['-tag:_[
---     '"TransferFromSuccessCallBack".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_[''zero.Qid],'_;_['_:_[
---     ''initiator.Qid,''_sender.Qid],'_;_['_:_[''sender.Qid,''from.Qid],'_;_['_:_[''recipient.Qid,''to.Qid],'_:_[
---     ''amount.Qid,''amount.Qid]]]]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''two_msgs.Qid,''msg_to_recipient.Qid,
---     ''msg_to_sender.Qid]]],'enviar_[''msgs.Qid]]]]]]]]]],'opcionMatch__['false.Bool,'__['_=_[''err.Qid,'aplicarF_[
---     ''CodeInsufficientAllowance.Qid]],'aplicarF_['__[''ThrowError.Qid,''err.Qid]]]]]]]]]]]]]]]]]    
--- ,'mv.Memoria,'mv.Memoria], unbounded) .

--- ***Contrato7
--- red metaRewrite(upModule('REGLAS, true), '`[_`,_`,_`]['Contrato_______['0.Zero,'import_['BoolUtils.LibImportar],'__['NombreLibreria_[''ZilGame.Qid],

--- '__['let__[
---     ''one_msg.Qid,'funcion__['_:_[''msg.Qid,'Message.NombreTipo],'let__in_[''nil_msg.Qid,'Nil`{_`}[
---     'Message.NombreTipo],'Cons___['Message.NombreTipo,''msg.Qid,''nil_msg.Qid]]]],

---     '__['let__[''no_msg.Qid,'Nil`{_`}['Message.NombreTipo]],

---     '__['let__[''hash_dist.Qid,'funcion__['_:_[''h0.Qid,'ByStr32.NombreTipo],'funcion__['_:_[
---     ''h1.Qid,'ByStr32.NombreTipo],'let__in_[''h00.Qid,'builtin_['__['to-uint256.TipoOpto,''h0.Qid]],'let__in_[
---     ''h11.Qid,'builtin_['__['to-uint256.TipoOpto,''h1.Qid]],'let__in_[''lt.Qid,'builtin_['_<._[''h00.Qid,''h11.Qid]],
---     'match__[''lt.Qid,'__['opcionMatch__['false.Bool,'builtin_['_-_[''h00.Qid,''h11.Qid]]],'opcionMatch__['true.Bool,
---     'builtin_['_-_[''h11.Qid,''h00.Qid]]]]]]]]]]],

---     '__['let__[''update_hash.Qid,'funcion__['_:_[''oh.Qid,'Option_[
---     'ByStr32.NombreTipo]],'funcion__['_:_[''h.Qid,'ByStr32.NombreTipo],'match__[''oh.Qid,'__['opcionMatch__['Some_[
---     ''x.Qid],'Some__['ByStr32.NombreTipo,''x.Qid]],'opcionMatch__['None.Option,'Some__['ByStr32.NombreTipo,
---     ''h.Qid]]]]]]],

---     '__['let__[''update_timer.Qid,'funcion__['_:_[''tm.Qid,'Option_['BNum.NombreTipo]],'funcion__['_:_[
---     ''b.Qid,'BNum.NombreTipo],'match__[''tm.Qid,'__['opcionMatch__['Some_[''x.Qid],'Some__['BNum.NombreTipo,''x.Qid]],
---     'opcionMatch__['None.Option,'let__in_[''window.Qid,'__['Uint32.TipoEntero,'s_^11['0.Zero]],'let__in_[''b1.Qid,
---     'builtin_['_+._[''b.Qid,''window.Qid]],'Some__['BNum.NombreTipo,''b1.Qid]]]]]]]]],

---     '__['let__[''can_play.Qid,
---     'funcion__['_:_[''tm.Qid,'Option_['BNum.NombreTipo]],'funcion__['_:_[''b.Qid,'BNum.NombreTipo],'match__[''tm.Qid,
---     '__['opcionMatch__['None.Option,'true.Bool],'opcionMatch__['Some_[''b1.Qid],'builtin_['_<._[''b.Qid,
---     ''b1.Qid]]]]]]]],

---     '__['let__[''time_to_claim.Qid,'funcion__['_:_[''tm.Qid,'Option_['BNum.NombreTipo]],'funcion__[
---     '_:_[''b.Qid,'BNum.NombreTipo],'match__[''tm.Qid,'__['opcionMatch__['None.Option,'false.Bool],'opcionMatch__[
---     'Some_[''b1.Qid],'let__in_[''c1.Qid,'builtin_['_<._[''b.Qid,''b1.Qid]],'negb_[''c1.Qid]]]]]]]],

---     '__['let__[
---     ''check_validity.Qid,'funcion__['_:_[''a.Qid,'ByStr20.NombreTipo],'funcion__['_:_[''solution.Qid,
---     'Int128.TipoEntero],'funcion__['_:_[''pa.Qid,'ByStr20.NombreTipo],'funcion__['_:_[''pb.Qid,'ByStr20.NombreTipo],
---     'funcion__['_:_[''guess_a.Qid,'Option_['ByStr32.NombreTipo]],'funcion__['_:_[''guess_b.Qid,'Option_[
---     'ByStr32.NombreTipo]],'let__in_[''ca.Qid,'builtin_['_==._[''pa.Qid,''a.Qid]],'let__in_[''cb.Qid,'builtin_['_==._[
---     ''pb.Qid,''a.Qid]],'let__in_[''xa.Qid,'Pair____['Bool.NombreTipo,'Option_['ByStr32.NombreTipo],''ca.Qid,
---     ''guess_a.Qid],'let__in_[''xb.Qid,'Pair____['Bool.NombreTipo,'Option_['ByStr32.NombreTipo],''cb.Qid,''guess_b.Qid],
---     'match__[''xa.Qid,'__['opcionMatch__['Pair__['true.Bool,'Some_[''g.Qid]],'let__in_[''h.Qid,'builtin_['sha256hash_[
---     ''solution.Qid]],'builtin_['_==._[''h.Qid,''g.Qid]]]],'opcionMatch__[''_.Qid,'match__[''xb.Qid,'__[
---     'opcionMatch__['Pair__['true.Bool,'Some_[''g.Qid]],'let__in_[''h.Qid,'builtin_['sha256hash_[''solution.Qid]],
---     'builtin_['_==._[''h.Qid,''g.Qid]]]],'opcionMatch__[''_.Qid,'false.Bool]]]]]]]]]]]]]]]]],

---     '__['let__[
---     ''can_withdraw.Qid,'funcion__['_:_[''tm.Qid,'BNum.NombreTipo],'funcion__['_:_[''b.Qid,'BNum.NombreTipo],'let__in_[
---     ''window.Qid,'__['Uint32.TipoEntero,'s_^30['0.Zero]],'let__in_[''deadline.Qid,'builtin_['_+._[''tm.Qid,
---     ''window.Qid]],'builtin_['_<._[''deadline.Qid,''b.Qid]]]]]]],

---     '__['let__[''determine_winner.Qid,'funcion__['_:_[
---     ''puzzle.Qid,'ByStr32.NombreTipo],'funcion__['_:_[''guess_a.Qid,'Option_['ByStr32.NombreTipo]],'funcion__['_:_[
---     ''guess_b.Qid,'Option_['ByStr32.NombreTipo]],'funcion__['_:_[''pa.Qid,'ByStr20.NombreTipo],'funcion__['_:_[
---     ''pb.Qid,'ByStr20.NombreTipo],'funcion__['_:_[''oa.Qid,'ByStr20.NombreTipo],'let__in_[''gab.Qid,'Pair____['Option_[
---     'ByStr32.NombreTipo],'Option_['ByStr32.NombreTipo],''guess_a.Qid,''guess_b.Qid],'match__[''gab.Qid,'__[
---     'opcionMatch__['Pair__['Some_[''ga.Qid],'Some_[''gb.Qid]],'let__in_[''c1.Qid,'builtin_['_<._[''d1.Qid,''d2.Qid]],
---     'match__[''c1.Qid,'__['opcionMatch__['true.Bool,''pa.Qid],'opcionMatch__['false.Bool,'let__in_[''c2.Qid,
---     'builtin_['_==._[''d1.Qid,''d2.Qid]],'match__[''c2.Qid,'__['opcionMatch__['false.Bool,''pb.Qid],
---     'opcionMatch__['true.Bool,''oa.Qid]]]]]]]]],'__['opcionMatch__['Pair__['Some_[''_.Qid],'None.Option],
---     ''pa.Qid],'__['opcionMatch__['Pair__['None.Option,'Some_[''_.Qid]],''pb.Qid],'opcionMatch__[
---     'Pair__['None.Option,'None.Option],''oa.Qid]]]]]]]]]]]]],

---     '__['let__[''solution_submitted.Qid,'__[
---     'Int32.TipoEntero,'s_['0.Zero]]],'__['let__[''time_window_missed.Qid,'__['Int32.TipoEntero,'s_^2['0.Zero]]],'__[
---     'let__[''not_a_player.Qid,'__['Int32.TipoEntero,'s_^3['0.Zero]]],'__['let__[''too_early_to_claim.Qid,'__[
---     'Int32.TipoEntero,'s_^4['0.Zero]]],'__['let__[''wrong__sender_or_solution.Qid,'__['Int32.TipoEntero,'s_^5[
---     '0.Zero]]],'__['let__[''here_is_the_reward.Qid,'__['Int32.TipoEntero,'s_^6['0.Zero]]],'let__[''cannot_withdraw.Qid,
---     '__['Int32.TipoEntero,'s_^7['0.Zero]]]]]]]]]]]]]]]]]]]],
    
	

	
--- 	'NombreContrato_[''ZilGame.Qid],
	
--- 	'_`,_['_:_[''owner.Qid,
---     'ByStr20.NombreTipo],'_`,_['_:_[''player_a.Qid,'ByStr20.NombreTipo],'_`,_['_:_[''player_b.Qid,'ByStr20.NombreTipo],
---     '_:_[''puzzle.Qid,'ByStr32.NombreTipo]]]],
	
--- 	'__['campo_=_['_:_[''player_a_hash.Qid,'Option_['ByStr32.NombreTipo]],
---     'None`{_`}['ByStr32.NombreTipo]],'__['campo_=_['_:_[''player_b_hash.Qid,'Option_['ByStr32.NombreTipo]],'None`{_`}[
---     'ByStr32.NombreTipo]],'campo_=_['_:_[''timer.Qid,'Option_['BNum.NombreTipo]],'None`{_`}['BNum.NombreTipo]]]],
	
--- 	'__[
---     'transicion___end[''Play.Qid,'_:_[''guess.Qid,'ByStr32.NombreTipo],'__['guardar__[''tm_opt.Qid,''timer.Qid],'__[
---     '_<-&BLOCKNUMBER[''b.Qid],'__['_=_[''c.Qid,'aplicarF_['__[''can_play.Qid,''tm_opt.Qid,''b.Qid]]],'match__[
---     ''c.Qid,'__['opcionMatch__['false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[
---     ''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''time_window_missed.Qid]]],'__[
---     '_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]],'opcionMatch__[
---     'true.Bool,'__['_=_[''isa.Qid,'builtin_['_==._[''_sender.Qid,''player_a.Qid]]],'__['_=_[''isb.Qid,'builtin_['_==._[
---     ''_sender.Qid,''player_b.Qid]]],'__['_=_[''tt.Qid,'true.Bool],'match__[''isa.Qid,'__['opcionMatch__['true.Bool,'__[
---     'guardar__[''ah.Qid,''player_a_hash.Qid],'__['_=_[''hopt.Qid,'aplicarF_['__[''update_hash.Qid,''ah.Qid,
---     ''guess.Qid]]],'__['actualizar__[''player_a_hash.Qid,''hopt.Qid],'__['_=_[''tm1.Qid,'aplicarF_['__[
---     ''update_timer.Qid,''tm_opt.Qid,''b.Qid]]],'__['actualizar__[''timer.Qid,''tm1.Qid],'__['_=_[''msg.Qid,
---     '`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[
---     ''code.Qid,''solution_submitted.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],
---     'enviar_[''msgs.Qid]]]]]]]]],'opcionMatch__['false.Bool,'match__[''isb.Qid,'__['opcionMatch__['true.Bool,'__[
---     'guardar__[''bh.Qid,''player_b_hash.Qid],'__['_=_[''hopt.Qid,'aplicarF_['__[''update_hash.Qid,''bh.Qid,
---     ''guess.Qid]]],'__['actualizar__[''player_b_hash.Qid,''hopt.Qid],'__['_=_[''tm1.Qid,'aplicarF_['__[
---     ''update_timer.Qid,''tm_opt.Qid,''b.Qid]]],'__['actualizar__[''timer.Qid,''tm1.Qid],'__['_=_[''msg.Qid,
---     '`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[
---     ''code.Qid,''solution_submitted.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],
---     'enviar_[''msgs.Qid]]]]]]]]],'opcionMatch__['false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],
---     'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''not_a_player.Qid]]],
---     '__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]]]]]]]]]]]]]]]]],
	
--- 	'__[
---     'transicion___end[''ClaimReward.Qid,'_:_[''solution.Qid,'Int128.TipoEntero],'__['guardar__[''tm_opt.Qid,
---     ''timer.Qid],'__['_<-&BLOCKNUMBER[''b.Qid],'__['_=_[''ttc.Qid,'aplicarF_['__[''time_to_claim.Qid,
---     ''tm_opt.Qid,''b.Qid]]],'match__[''ttc.Qid,'__['opcionMatch__['false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_[
---     '"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,
---     ''too_early_to_claim.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[
---     ''msgs.Qid]]]],'opcionMatch__['true.Bool,'__['guardar__[''pa.Qid,''player_a_hash.Qid],'__['guardar__[''pb.Qid,
---     ''player_b_hash.Qid],'__['_=_[''is_valid.Qid,'aplicarF_['__[''check_validity.Qid,''_sender.Qid,
---     ''solution.Qid,''player_a.Qid,''player_b.Qid,''pa.Qid,''pb.Qid]]],'match__[''is_valid.Qid,'__['opcionMatch__[
---     'false.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__[
---     'Uint128.TipoEntero,'0.Zero]],'_:_[''code.Qid,''wrong__sender_or_solution.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_[
---     '__[''one_msg.Qid,''msg.Qid]]],'enviar_[''msgs.Qid]]]],'opcionMatch__['true.Bool,'__['_=_[''winner.Qid,
---     'aplicarF_['__[''determine_winner.Qid,''puzzle.Qid,''pa.Qid,''pb.Qid,''player_a.Qid,''player_b.Qid,
---     ''owner.Qid]]],'__['guardar__[''bal.Qid,''_balance.Qid],'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],
---     'dirEnvio_[''winner.Qid],'cantidadEnvio_[''bal.Qid],'_:_[''code.Qid,''here_is_the_reward.Qid]]],'__['_=_[''ff.Qid,
---     'false.Bool],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,''msg.Qid]]],'enviar_[
---     ''msgs.Qid]]]]]]]]]]]]]]]]]]],
	
--- 	'transicion___end[''Withdraw.Qid,'lpv.ListaParamInm,'__['_=_[''tm.Qid,'aplicarF_[
---     ''_creation_block.Qid]],'__['_<-&BLOCKNUMBER[''b.Qid],'__['_=_[''cw.Qid,'aplicarF_['__[
---     ''can_withdraw.Qid,''tm.Qid,''b.Qid]]],'__['_=_[''is_owner.Qid,'builtin_['_==._[''owner.Qid,''_sender.Qid]]],'__[
---     'guardar__[''bal.Qid,''_balance.Qid],'__['_=_[''good_to_go.Qid,'_and_[''cw.Qid,''is_owner.Qid]],'match__[
---     ''good_to_go.Qid,'__['opcionMatch__['true.Bool,'__['_=_[''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[
---     ''owner.Qid],'cantidadEnvio_[''bal.Qid],'_:_[''code.Qid,''here_is_the_reward.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_[
---     '__[''one_msg.Qid,''msg.Qid]]],'__['_=_[''e.Qid,'`{_;_`}['-eventname:_['"GameOver".String],
---     'lcv.ListaCamposEvento]],'__['evento_[''e.Qid],'enviar_[''msgs.Qid]]]]]],'opcionMatch__['false.Bool,'__['_=_[
---     ''msg.Qid,'`{_;_;_;_`}['-tag:_['"".String],'dirEnvio_[''_sender.Qid],'cantidadEnvio_['__['Uint128.TipoEntero,
---     '0.Zero]],'_:_[''code.Qid,''cannot_withdraw.Qid]]],'__['_=_[''msgs.Qid,'aplicarF_['__[''one_msg.Qid,
---     ''msg.Qid]]],'enviar_[''msgs.Qid]]]]]]]]]]]]]]]]   
--- ,'mv.Memoria,'mv.Memoria], unbounded) .

***Ejecutar transicion 1
red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''player_a_hash.Qid,'None.Option],'Importaciones`[_`][
    'BoolUtils.LibImportar],'`[_=>_`][''owner.Qid,'ByStr20.NombreTipo],'`[_=>_`][''player_a.Qid,'s_^2['0.Zero]],
    '`[_=>_`][''player_b.Qid,'s_^2['0.Zero]],'`[_=>_`][''puzzle.Qid,'ByStr32.NombreTipo],'`[_=>_`][
    ''player_b_hash.Qid,'None`{_`}['ByStr32.NombreTipo]],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][''msg.Qid,
    'Message.NombreTipo],'`[_=>_`,_`][''nil_msg.Qid,'Nil`[_`]['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,
    ''nil_msg.Qid]]]],'`[_=>_`][''timer.Qid,'None.Option],'`[_=>_`][''no_msg.Qid,'Nil`{_`}['Message.NombreTipo]],
    '`[_=>_`][''hash_dist.Qid,'Funcion`[_`,_`]['`[_=>_`][''h0.Qid,'ByStr32.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][
    ''h1.Qid,'ByStr32.NombreTipo],'`[_=>_`,_`][''h00.Qid,'`[_`]['__['to-uint256.TipoOpto,''h0.Qid]],'`[_=>_`,_`][
    ''h11.Qid,'`[_`]['__['to-uint256.TipoOpto,''h1.Qid]],'`[_=>_`,_`][''lt.Qid,'`[_`]['_<._[''h00.Qid,''h11.Qid]],
    '`[_=>_`][''lt.Qid,'__['`[_=>_`]['false.Bool,'`[_`]['_-_[''h00.Qid,''h11.Qid]]],'`[_=>_`]['true.Bool,'`[_`]['_-_[
    ''h11.Qid,''h00.Qid]]]]]]]]]]],'`[_=>_`][''update_hash.Qid,'Funcion`[_`,_`]['`[_=>_`][''oh.Qid,'Option_[
    'ByStr32.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''h.Qid,'ByStr32.NombreTipo],'`[_=>_`][''oh.Qid,'__['`[_=>_`][
    'Some_[''x.Qid],'Some`[_`][''x.Qid]],'`[_=>_`]['None.Option,'Some`[_`][''h.Qid]]]]]]],'`[_=>_`][''update_timer.Qid,
    'Funcion`[_`,_`]['`[_=>_`][''tm.Qid,'Option_['BNum.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''b.Qid,
    'BNum.NombreTipo],'`[_=>_`][''tm.Qid,'__['`[_=>_`]['Some_[''x.Qid],'Some`[_`][''x.Qid]],'`[_=>_`]['None.Option,
    '`[_=>_`,_`][''window.Qid,'s_^11['0.Zero],'`[_=>_`,_`][''b1.Qid,'`[_`]['_+._[''b.Qid,''window.Qid]],'Some`[_`][
    ''b1.Qid]]]]]]]]],'`[_=>_`][''can_play.Qid,'Funcion`[_`,_`]['`[_=>_`][''tm.Qid,'Option_['BNum.NombreTipo]],
    'Funcion`[_`,_`]['`[_=>_`][''b.Qid,'BNum.NombreTipo],'`[_=>_`][''tm.Qid,'__['`[_=>_`]['None.Option,'true.Bool],
    '`[_=>_`]['Some_[''b1.Qid],'`[_`]['_<._[''b.Qid,''b1.Qid]]]]]]]],'`[_=>_`][''time_to_claim.Qid,'Funcion`[_`,_`][
    '`[_=>_`][''tm.Qid,'Option_['BNum.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''b.Qid,'BNum.NombreTipo],'`[_=>_`][
    ''tm.Qid,'__['`[_=>_`]['None.Option,'false.Bool],'`[_=>_`]['Some_[''b1.Qid],'`[_=>_`,_`][''c1.Qid,'`[_`]['_<._[
    ''b.Qid,''b1.Qid]],'`[_`]['negb_[''c1.Qid]]]]]]]]],'`[_=>_`][''check_validity.Qid,'Funcion`[_`,_`]['`[_=>_`][
    ''a.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''solution.Qid,'Int128.TipoEntero],'Funcion`[_`,_`][
    '`[_=>_`][''pa.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''pb.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`][
    '`[_=>_`][''guess_a.Qid,'Option_['ByStr32.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''guess_b.Qid,'Option_[
    'ByStr32.NombreTipo]],'`[_=>_`,_`][''ca.Qid,'`[_`]['_==._[''a.Qid,''pa.Qid]],'`[_=>_`,_`][''cb.Qid,'`[_`]['_==._[
    ''a.Qid,''pb.Qid]],'`[_=>_`,_`][''xa.Qid,'Par`[_`,_`][''ca.Qid,''guess_a.Qid],'`[_=>_`,_`][''xb.Qid,'Par`[_`,_`][
    ''cb.Qid,''guess_b.Qid],'`[_=>_`][''xa.Qid,'__['`[_=>_`]['Pair__['true.Bool,'Some_[''g.Qid]],'`[_=>_`,_`][''h.Qid,
    '`[_`]['sha256hash_[''solution.Qid]],'`[_`]['_==._[''g.Qid,''h.Qid]]]],'`[_=>_`][''_.Qid,'`[_=>_`][''xb.Qid,'__[
    '`[_=>_`]['Pair__['true.Bool,'Some_[''g.Qid]],'`[_=>_`,_`][''h.Qid,'`[_`]['sha256hash_[''solution.Qid]],'`[_`][
    '_==._[''g.Qid,''h.Qid]]]],'`[_=>_`][''_.Qid,'false.Bool]]]]]]]]]]]]]]]]],'`[_=>_`][''can_withdraw.Qid,
    'Funcion`[_`,_`]['`[_=>_`][''tm.Qid,'BNum.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''b.Qid,'BNum.NombreTipo],
    '`[_=>_`,_`][''window.Qid,'s_^30['0.Zero],'`[_=>_`,_`][''deadline.Qid,'`[_`]['_+._[''tm.Qid,''window.Qid]],'`[_`][
    '_<._[''deadline.Qid,''b.Qid]]]]]]],'`[_=>_`][''determine_winner.Qid,'Funcion`[_`,_`]['`[_=>_`][''puzzle.Qid,
    'ByStr32.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''guess_a.Qid,'Option_['ByStr32.NombreTipo]],'Funcion`[_`,_`][
    '`[_=>_`][''guess_b.Qid,'Option_['ByStr32.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''pa.Qid,'ByStr20.NombreTipo],
    'Funcion`[_`,_`]['`[_=>_`][''pb.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''oa.Qid,'ByStr20.NombreTipo],
    '`[_=>_`,_`][''gab.Qid,'Par`[_`,_`][''guess_a.Qid,''guess_b.Qid],'`[_=>_`][''gab.Qid,'__['`[_=>_`]['Pair__['Some_[
    ''ga.Qid],'Some_[''gb.Qid]],'`[_=>_`,_`][''c1.Qid,'`[_`]['_<._[''d1.Qid,''d2.Qid]],'`[_=>_`][''c1.Qid,'__[
    '`[_=>_`]['true.Bool,''pa.Qid],'`[_=>_`]['false.Bool,'`[_=>_`,_`][''c2.Qid,'`[_`]['_==._[''d1.Qid,''d2.Qid]],
    '`[_=>_`][''c2.Qid,'__['`[_=>_`]['false.Bool,''pb.Qid],'`[_=>_`]['true.Bool,''oa.Qid]]]]]]]]],'`[_=>_`]['Pair__[
    'Some_[''_.Qid],'None.Option],''pa.Qid],'`[_=>_`]['Pair__['None.Option,'Some_[''_.Qid]],''pb.Qid],'`[_=>_`][
    'Pair__['None.Option,'None.Option],''oa.Qid]]]]]]]]]]],'`[_=>_`][''solution_submitted.Qid,'s_['0.Zero]],'`[_=>_`][
    ''time_window_missed.Qid,'s_^2['0.Zero]],'`[_=>_`][''not_a_player.Qid,'s_^3['0.Zero]],'`[_=>_`][
    ''too_early_to_claim.Qid,'s_^4['0.Zero]],'`[_=>_`][''wrong__sender_or_solution.Qid,'s_^5['0.Zero]],'`[_=>_`][
    ''here_is_the_reward.Qid,'s_^6['0.Zero]],'`[_=>_`][''cannot_withdraw.Qid,'s_^7['0.Zero]]],

    '`[_`,_`,_`,_`,_`][
    ''Play.Qid,'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['`[_=>_`][''tm_opt.Qid,''timer.Qid],'NumBloque`[_`][
    ''b.Qid],'`[_=>_`][''c.Qid,'AplicarF`[_`,_`][''can_play.Qid,'__[''tm_opt.Qid,''b.Qid]]],'`[_=>_`][''c.Qid,'__[
    '`[_=>_`]['false.Bool,'__['`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,
    ''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''time_window_missed.Qid]]],'`[_=>_`][
    ''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['true.Bool,
    '__['`[_=>_`][''isa.Qid,'`[_`]['_==._[''_sender.Qid,''player_a.Qid]]],'`[_=>_`][''isb.Qid,'`[_`]['_==._[
    ''_sender.Qid,''player_b.Qid]]],'`[_=>_`][''tt.Qid,'`[_`]['true.Bool]],'`[_=>_`][''isa.Qid,'__['`[_=>_`][
    'true.Bool,'__['`[_=>_`][''ah.Qid,''player_a_hash.Qid],'`[_=>_`][''hopt.Qid,'AplicarF`[_`,_`][''update_hash.Qid,
    '__[''ah.Qid,''guess.Qid]]],'Actualizar`[_`,_`][''player_a_hash.Qid,''hopt.Qid],'`[_=>_`][''tm1.Qid,
    'AplicarF`[_`,_`][''update_timer.Qid,'__[''tm_opt.Qid,''b.Qid]]],'Actualizar`[_`,_`][''timer.Qid,''tm1.Qid],
    '`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][
    ''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''solution_submitted.Qid]]],'`[_=>_`][''msgs.Qid,
    'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['false.Bool,'`[_=>_`][
    ''isb.Qid,'__['`[_=>_`]['true.Bool,'__['`[_=>_`][''bh.Qid,''player_b_hash.Qid],'`[_=>_`][''hopt.Qid,
    'AplicarF`[_`,_`][''update_hash.Qid,'__[''bh.Qid,''guess.Qid]]],'Actualizar`[_`,_`][''player_b_hash.Qid,
    ''hopt.Qid],'`[_=>_`][''tm1.Qid,'AplicarF`[_`,_`][''update_timer.Qid,'__[''tm_opt.Qid,''b.Qid]]],
    'Actualizar`[_`,_`][''timer.Qid,''tm1.Qid],'`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][
    ''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,
    ''solution_submitted.Qid]]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][
    ''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['false.Bool,'__['`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],
    '`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,
    ''not_a_player.Qid]]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,
    ''msgs.Qid]]]]]]]]]]]]],'__['`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,
    's_^2['0.Zero]],'`[_=>_`][''guess.Qid,'ByStr32.NombreTipo]]]], unbounded) .
--- ***Ejecutar transicion 2
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''player_a_hash.Qid,'None.Option],'Importaciones`[_`][
---     'BoolUtils.LibImportar],'`[_=>_`][''owner.Qid,'ByStr20.NombreTipo],'`[_=>_`][''player_a.Qid,'ByStr20.NombreTipo],
---     '`[_=>_`][''player_b.Qid,'ByStr20.NombreTipo],'`[_=>_`][''puzzle.Qid,'ByStr32.NombreTipo],'`[_=>_`][
---     ''player_b_hash.Qid,'None.Option],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][''msg.Qid,
---     'Message.NombreTipo],'`[_=>_`,_`][''nil_msg.Qid,'Nil`[_`]['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,
---     ''nil_msg.Qid]]]],'`[_=>_`][''timer.Qid,'None.Option],'`[_=>_`][''no_msg.Qid,'Nil`{_`}['Message.NombreTipo]],
---     '`[_=>_`][''hash_dist.Qid,'Funcion`[_`,_`]['`[_=>_`][''h0.Qid,'ByStr32.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][
---     ''h1.Qid,'ByStr32.NombreTipo],'`[_=>_`,_`][''h00.Qid,'`[_`]['__['to-uint256.TipoOpto,''h0.Qid]],'`[_=>_`,_`][
---     ''h11.Qid,'`[_`]['__['to-uint256.TipoOpto,''h1.Qid]],'`[_=>_`,_`][''lt.Qid,'`[_`]['_<._[''h00.Qid,''h11.Qid]],
---     '`[_=>_`][''lt.Qid,'__['`[_=>_`]['false.Bool,'`[_`]['_-_[''h00.Qid,''h11.Qid]]],'`[_=>_`]['true.Bool,'`[_`]['_-_[
---     ''h11.Qid,''h00.Qid]]]]]]]]]]],'`[_=>_`][''update_hash.Qid,'Funcion`[_`,_`]['`[_=>_`][''oh.Qid,'Option_[
---     'ByStr32.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''h.Qid,'ByStr32.NombreTipo],'`[_=>_`][''oh.Qid,'__['`[_=>_`][
---     'Some_[''x.Qid],'Some`[_`][''x.Qid]],'`[_=>_`]['None.Option,'Some`[_`][''h.Qid]]]]]]],'`[_=>_`][''update_timer.Qid,
---     'Funcion`[_`,_`]['`[_=>_`][''tm.Qid,'Option_['BNum.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''b.Qid,
---     'BNum.NombreTipo],'`[_=>_`][''tm.Qid,'__['`[_=>_`]['Some_[''x.Qid],'Some`[_`][''x.Qid]],'`[_=>_`]['None.Option,
---     '`[_=>_`,_`][''window.Qid,'s_^11['0.Zero],'`[_=>_`,_`][''b1.Qid,'`[_`]['_+._[''b.Qid,''window.Qid]],'Some`[_`][
---     ''b1.Qid]]]]]]]]],'`[_=>_`][''can_play.Qid,'Funcion`[_`,_`]['`[_=>_`][''tm.Qid,'Option_['BNum.NombreTipo]],
---     'Funcion`[_`,_`]['`[_=>_`][''b.Qid,'BNum.NombreTipo],'`[_=>_`][''tm.Qid,'__['`[_=>_`]['None.Option,'true.Bool],
---     '`[_=>_`]['Some_[''b1.Qid],'`[_`]['_<._[''b.Qid,''b1.Qid]]]]]]]],'`[_=>_`][''time_to_claim.Qid,'Funcion`[_`,_`][
---     '`[_=>_`][''tm.Qid,'Option_['BNum.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''b.Qid,'BNum.NombreTipo],'`[_=>_`][
---     ''tm.Qid,'__['`[_=>_`]['None.Option,'false.Bool],'`[_=>_`]['Some_[''b1.Qid],'`[_=>_`,_`][''c1.Qid,'`[_`]['_<._[
---     ''b.Qid,''b1.Qid]],'`[_`]['negb_[''c1.Qid]]]]]]]]],'`[_=>_`][''check_validity.Qid,'Funcion`[_`,_`]['`[_=>_`][
---     ''a.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''solution.Qid,'Int128.TipoEntero],'Funcion`[_`,_`][
---     '`[_=>_`][''pa.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''pb.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`][
---     '`[_=>_`][''guess_a.Qid,'Option_['ByStr32.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''guess_b.Qid,'Option_[
---     'ByStr32.NombreTipo]],'`[_=>_`,_`][''ca.Qid,'`[_`]['_==._[''a.Qid,''pa.Qid]],'`[_=>_`,_`][''cb.Qid,'`[_`]['_==._[
---     ''a.Qid,''pb.Qid]],'`[_=>_`,_`][''xa.Qid,'Par`[_`,_`][''ca.Qid,''guess_a.Qid],'`[_=>_`,_`][''xb.Qid,'Par`[_`,_`][
---     ''cb.Qid,''guess_b.Qid],'`[_=>_`][''xa.Qid,'__['`[_=>_`]['Pair__['true.Bool,'Some_[''g.Qid]],'`[_=>_`,_`][''h.Qid,
---     '`[_`]['sha256hash_[''solution.Qid]],'`[_`]['_==._[''g.Qid,''h.Qid]]]],'`[_=>_`][''_.Qid,'`[_=>_`][''xb.Qid,'__[
---     '`[_=>_`]['Pair__['true.Bool,'Some_[''g.Qid]],'`[_=>_`,_`][''h.Qid,'`[_`]['sha256hash_[''solution.Qid]],'`[_`][
---     '_==._[''g.Qid,''h.Qid]]]],'`[_=>_`][''_.Qid,'false.Bool]]]]]]]]]]]]]]]]],'`[_=>_`][''can_withdraw.Qid,
---     'Funcion`[_`,_`]['`[_=>_`][''tm.Qid,'BNum.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''b.Qid,'BNum.NombreTipo],
---     '`[_=>_`,_`][''window.Qid,'s_^30['0.Zero],'`[_=>_`,_`][''deadline.Qid,'`[_`]['_+._[''tm.Qid,''window.Qid]],'`[_`][
---     '_<._[''deadline.Qid,''b.Qid]]]]]]],'`[_=>_`][''determine_winner.Qid,'Funcion`[_`,_`]['`[_=>_`][''puzzle.Qid,
---     'ByStr32.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''guess_a.Qid,'Option_['ByStr32.NombreTipo]],'Funcion`[_`,_`][
---     '`[_=>_`][''guess_b.Qid,'Option_['ByStr32.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''pa.Qid,'ByStr20.NombreTipo],
---     'Funcion`[_`,_`]['`[_=>_`][''pb.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''oa.Qid,'ByStr20.NombreTipo],
---     '`[_=>_`,_`][''gab.Qid,'Par`[_`,_`][''guess_a.Qid,''guess_b.Qid],'`[_=>_`][''gab.Qid,'__['`[_=>_`]['Pair__['Some_[
---     ''ga.Qid],'Some_[''gb.Qid]],'`[_=>_`,_`][''c1.Qid,'`[_`]['_<._[''d1.Qid,''d2.Qid]],'`[_=>_`][''c1.Qid,'__[
---     '`[_=>_`]['true.Bool,''pa.Qid],'`[_=>_`]['false.Bool,'`[_=>_`,_`][''c2.Qid,'`[_`]['_==._[''d1.Qid,''d2.Qid]],
---     '`[_=>_`][''c2.Qid,'__['`[_=>_`]['false.Bool,''pb.Qid],'`[_=>_`]['true.Bool,''oa.Qid]]]]]]]]],'`[_=>_`]['Pair__[
---     'Some_[''_.Qid],'None.Option],''pa.Qid],'`[_=>_`]['Pair__['None.Option,'Some_[''_.Qid]],''pb.Qid],'`[_=>_`][
---     'Pair__['None.Option,'None.Option],''oa.Qid]]]]]]]]]]],'`[_=>_`][''solution_submitted.Qid,'s_['0.Zero]],'`[_=>_`][
---     ''time_window_missed.Qid,'s_^2['0.Zero]],'`[_=>_`][''not_a_player.Qid,'s_^3['0.Zero]],'`[_=>_`][
---     ''too_early_to_claim.Qid,'s_^4['0.Zero]],'`[_=>_`][''wrong__sender_or_solution.Qid,'s_^5['0.Zero]],'`[_=>_`][
---     ''here_is_the_reward.Qid,'s_^6['0.Zero]],'`[_=>_`][''cannot_withdraw.Qid,'s_^7['0.Zero]]],
    
---     '`[_`,_`,_`,_`,_`][''ClaimReward.Qid,
---     'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['`[_=>_`][''tm_opt.Qid,''timer.Qid],'NumBloque`[_`][''b.Qid],
---     '`[_=>_`][''ttc.Qid,'true.Bool],'`[_=>_`][''ttc.Qid,'__[
---     '`[_=>_`]['false.Bool,'__['`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,
---     ''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,''too_early_to_claim.Qid]]],'`[_=>_`][
---     ''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['true.Bool,
---     '__['`[_=>_`][''pa.Qid,''player_a_hash.Qid],'`[_=>_`][''pb.Qid,''player_b_hash.Qid],'`[_=>_`][''is_valid.Qid,
---     'true.Bool],'`[_=>_`][''is_valid.Qid,'__['`[_=>_`]['false.Bool,'__['`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,
---     '"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],'`[_=>_`][''code.Qid,
---     ''wrong__sender_or_solution.Qid]]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][
---     ''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['true.Bool,'__['`[_=>_`][''winner.Qid,'AplicarF`[_`,_`][
---     ''determine_winner.Qid,'__[''puzzle.Qid,''pa.Qid,''pb.Qid,''player_a.Qid,''player_b.Qid,''owner.Qid]]],'`[_=>_`][
---     ''bal.Qid,''_balance.Qid],'`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,
---     ''winner.Qid],'`[_=>_`][''cantidadEnvio.Qid,''bal.Qid],'`[_=>_`][''code.Qid,''here_is_the_reward.Qid]]],'`[_=>_`][
---     ''ff.Qid,'`[_`]['false.Bool]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][
---     ''enviar.Qid,''msgs.Qid]]]]]]]]]],'__['`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,
---     'ByStr20.NombreTipo],'`[_=>_`][''solution.Qid,'Int128.TipoEntero]]]], unbounded) .
--- ***Ejecutar transicion 3 (solucionar problema de las variables repetidas y aplicar la funcion)
--- red metaRewrite(upModule('REGLAS-EJECUTAR, true), '`[_`,_`]['__['`[_=>_`][''player_a_hash.Qid,'None.Option],'Importaciones`[_`][
---     'BoolUtils.LibImportar],'`[_=>_`][''owner.Qid,'s_['0.Zero]],'`[_=>_`][''player_a.Qid,'ByStr20.NombreTipo],
---     '`[_=>_`][''player_b.Qid,'ByStr20.NombreTipo],'`[_=>_`][''puzzle.Qid,'ByStr32.NombreTipo],'`[_=>_`][
---     ''player_b_hash.Qid,'None`{_`}['ByStr32.NombreTipo]],'`[_=>_`][''one_msg.Qid,'Funcion`[_`,_`]['`[_=>_`][''msg.Qid,
---     'Message.NombreTipo],'`[_=>_`,_`][''nil_msg.Qid,'Nil`[_`]['Message.NombreTipo],'Cons`[_`,_`][''msg.Qid,
---     ''nil_msg.Qid]]]],'`[_=>_`][''timer.Qid,'None.Option],'`[_=>_`][''no_msg.Qid,'Nil`{_`}['Message.NombreTipo]],
---     '`[_=>_`][''hash_dist.Qid,'Funcion`[_`,_`]['`[_=>_`][''h0.Qid,'ByStr32.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][
---     ''h1.Qid,'ByStr32.NombreTipo],'`[_=>_`,_`][''h00.Qid,'`[_`]['__['to-uint256.TipoOpto,''h0.Qid]],'`[_=>_`,_`][
---     ''h11.Qid,'`[_`]['__['to-uint256.TipoOpto,''h1.Qid]],'`[_=>_`,_`][''lt.Qid,'`[_`]['_<._[''h00.Qid,''h11.Qid]],
---     '`[_=>_`][''lt.Qid,'__['`[_=>_`]['false.Bool,'`[_`]['_-_[''h00.Qid,''h11.Qid]]],'`[_=>_`]['true.Bool,'`[_`]['_-_[
---     ''h11.Qid,''h00.Qid]]]]]]]]]]],'`[_=>_`][''update_hash.Qid,'Funcion`[_`,_`]['`[_=>_`][''oh.Qid,'Option_[
---     'ByStr32.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''h.Qid,'ByStr32.NombreTipo],'`[_=>_`][''oh.Qid,'__['`[_=>_`][
---     'Some_[''x.Qid],'Some`[_`][''x.Qid]],'`[_=>_`]['None.Option,'Some`[_`][''h.Qid]]]]]]],'`[_=>_`][''update_timer.Qid,
---     'Funcion`[_`,_`]['`[_=>_`][''tm.Qid,'Option_['BNum.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''b.Qid,
---     'BNum.NombreTipo],'`[_=>_`][''tm.Qid,'__['`[_=>_`]['Some_[''x.Qid],'Some`[_`][''x.Qid]],'`[_=>_`]['None.Option,
---     '`[_=>_`,_`][''window.Qid,'s_^11['0.Zero],'`[_=>_`,_`][''b1.Qid,'`[_`]['_+._[''b.Qid,''window.Qid]],'Some`[_`][
---     ''b1.Qid]]]]]]]]],'`[_=>_`][''can_play.Qid,'Funcion`[_`,_`]['`[_=>_`][''tm.Qid,'Option_['BNum.NombreTipo]],
---     'Funcion`[_`,_`]['`[_=>_`][''b.Qid,'BNum.NombreTipo],'`[_=>_`][''tm.Qid,'__['`[_=>_`]['None.Option,'true.Bool],
---     '`[_=>_`]['Some_[''b1.Qid],'`[_`]['_<._[''b.Qid,''b1.Qid]]]]]]]],'`[_=>_`][''time_to_claim.Qid,'Funcion`[_`,_`][
---     '`[_=>_`][''tm.Qid,'Option_['BNum.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''b.Qid,'BNum.NombreTipo],'`[_=>_`][
---     ''tm.Qid,'__['`[_=>_`]['None.Option,'false.Bool],'`[_=>_`]['Some_[''b1.Qid],'`[_=>_`,_`][''c1.Qid,'`[_`]['_<._[
---     ''b.Qid,''b1.Qid]],'`[_`]['negb_[''c1.Qid]]]]]]]]],'`[_=>_`][''check_validity.Qid,'Funcion`[_`,_`]['`[_=>_`][
---     ''a.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''solution.Qid,'Int128.TipoEntero],'Funcion`[_`,_`][
---     '`[_=>_`][''pa.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''pb.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`][
---     '`[_=>_`][''guess_a.Qid,'Option_['ByStr32.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''guess_b.Qid,'Option_[
---     'ByStr32.NombreTipo]],'`[_=>_`,_`][''ca.Qid,'`[_`]['_==._[''a.Qid,''pa.Qid]],'`[_=>_`,_`][''cb.Qid,'`[_`]['_==._[
---     ''a.Qid,''pb.Qid]],'`[_=>_`,_`][''xa.Qid,'Par`[_`,_`][''ca.Qid,''guess_a.Qid],'`[_=>_`,_`][''xb.Qid,'Par`[_`,_`][
---     ''cb.Qid,''guess_b.Qid],'`[_=>_`][''xa.Qid,'__['`[_=>_`]['Pair__['true.Bool,'Some_[''g.Qid]],'`[_=>_`,_`][''h.Qid,
---     '`[_`]['sha256hash_[''solution.Qid]],'`[_`]['_==._[''g.Qid,''h.Qid]]]],'`[_=>_`][''_.Qid,'`[_=>_`][''xb.Qid,'__[
---     '`[_=>_`]['Pair__['true.Bool,'Some_[''g.Qid]],'`[_=>_`,_`][''h.Qid,'`[_`]['sha256hash_[''solution.Qid]],'`[_`][
---     '_==._[''g.Qid,''h.Qid]]]],'`[_=>_`][''_.Qid,'false.Bool]]]]]]]]]]]]]]]]],'`[_=>_`][''can_withdraw.Qid,
---     'Funcion`[_`,_`]['`[_=>_`][''tm.Qid,'BNum.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''b.Qid,'BNum.NombreTipo],
---     '`[_=>_`,_`][''window.Qid,'s_^30['0.Zero],'`[_=>_`,_`][''deadline.Qid,'`[_`]['_+._[''tm.Qid,''window.Qid]],'`[_`][
---     '_<._[''deadline.Qid,''b.Qid]]]]]]],'`[_=>_`][''determine_winner.Qid,'Funcion`[_`,_`]['`[_=>_`][''puzzle.Qid,
---     'ByStr32.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''guess_a.Qid,'Option_['ByStr32.NombreTipo]],'Funcion`[_`,_`][
---     '`[_=>_`][''guess_b.Qid,'Option_['ByStr32.NombreTipo]],'Funcion`[_`,_`]['`[_=>_`][''pa.Qid,'ByStr20.NombreTipo],
---     'Funcion`[_`,_`]['`[_=>_`][''pb.Qid,'ByStr20.NombreTipo],'Funcion`[_`,_`]['`[_=>_`][''oa.Qid,'ByStr20.NombreTipo],
---     '`[_=>_`,_`][''gab.Qid,'Par`[_`,_`][''guess_a.Qid,''guess_b.Qid],'`[_=>_`][''gab.Qid,'__['`[_=>_`]['Pair__['Some_[
---     ''ga.Qid],'Some_[''gb.Qid]],'`[_=>_`,_`][''c1.Qid,'`[_`]['_<._[''d1.Qid,''d2.Qid]],'`[_=>_`][''c1.Qid,'__[
---     '`[_=>_`]['true.Bool,''pa.Qid],'`[_=>_`]['false.Bool,'`[_=>_`,_`][''c2.Qid,'`[_`]['_==._[''d1.Qid,''d2.Qid]],
---     '`[_=>_`][''c2.Qid,'__['`[_=>_`]['false.Bool,''pb.Qid],'`[_=>_`]['true.Bool,''oa.Qid]]]]]]]]],'`[_=>_`]['Pair__[
---     'Some_[''_.Qid],'None.Option],''pa.Qid],'`[_=>_`]['Pair__['None.Option,'Some_[''_.Qid]],''pb.Qid],'`[_=>_`][
---     'Pair__['None.Option,'None.Option],''oa.Qid]]]]]]]]]]],'`[_=>_`][''solution_submitted.Qid,'s_['0.Zero]],'`[_=>_`][
---     ''time_window_missed.Qid,'s_^2['0.Zero]],'`[_=>_`][''not_a_player.Qid,'s_^3['0.Zero]],'`[_=>_`][
---     ''too_early_to_claim.Qid,'s_^4['0.Zero]],'`[_=>_`][''wrong__sender_or_solution.Qid,'s_^5['0.Zero]],'`[_=>_`][
---     ''here_is_the_reward.Qid,'s_^6['0.Zero]],'`[_=>_`][''cannot_withdraw.Qid,'s_^7['0.Zero]]],
    
---     '`[_`,_`,_`,_`,_`][''Withdraw.Qid,
---     'lpv.ListaParamInm,'ldv.ListaDeclaraciones,'__['`[_=>_`][''tm.Qid,'s_^7['0.Zero]],
---     'NumBloque`[_`][''b.Qid],'`[_=>_`][''cw.Qid,'AplicarF`[_`,_`][''can_withdraw.Qid,'__[''tm.Qid,''b.Qid]]],'`[_=>_`][
---     ''is_owner.Qid,'`[_`]['_==._[''_sender.Qid,''owner.Qid]]],'`[_=>_`][''bal.Qid,'s_['0.Zero]],'`[_=>_`][
---     ''good_to_go.Qid,'`[_`]['_and_[''cw.Qid,''is_owner.Qid]]],'`[_=>_`][''good_to_go.Qid,'__['`[_=>_`]['true.Bool,'__[
---     '`[_=>_`][''msg.Qid,'__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''owner.Qid],'`[_=>_`][
---     ''cantidadEnvio.Qid,''bal.Qid],'`[_=>_`][''code.Qid,''here_is_the_reward.Qid]]],'`[_=>_`][''msgs.Qid,
---     'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],'`[_=>_`][''e.Qid,'`[_=>_`][''eventname.Qid,'"GameOver".String]],
---     '`[_=>_`][''evento.Qid,''e.Qid],'`[_=>_`][''enviar.Qid,''msgs.Qid]]],'`[_=>_`]['false.Bool,'__['`[_=>_`][''msg.Qid,
---     '__['`[_=>_`][''tag.Qid,'"".String],'`[_=>_`][''dirEnvio.Qid,''_sender.Qid],'`[_=>_`][''cantidadEnvio.Qid,'0.Zero],
---     '`[_=>_`][''code.Qid,''cannot_withdraw.Qid]]],'`[_=>_`][''msgs.Qid,'AplicarF`[_`,_`][''one_msg.Qid,''msg.Qid]],
---     '`[_=>_`][''enviar.Qid,''msgs.Qid]]]]]],'__['`[_=>_`][''_amount.Qid,'Uint128.TipoEntero],'`[_=>_`][''_sender.Qid,
---     'ByStr20.NombreTipo]]]], unbounded) .








set print attribute on .

erew run .